import * as stylex from '@stylexjs/stylex';
import { media } from '@/styles/constants.stylex';
import { colors, effects, layout, typography } from '@/styles/tokens.stylex';

export const courseDetailStyles = stylex.create({
  courseDetailPage: {
    marginInline: 'auto',
    maxWidth: '73.75rem',
    minWidth: 0,
    width: '100%',
  },
  courseWorkspaceHeader: {
    gap: '1rem',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '.75rem',
    minHeight: {
      default: '3.75rem',
      [media.mobile]: '3.25rem',
    },
  },
  courseWorkspaceIdentity: {
    gap: {
      default: '.6rem',
      [media.mobile]: '.35rem',
    },
    alignItems: 'center',
    display: 'flex',
    flexBasis: '0%',
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  courseBackButton: {
    color: colors.textSecondary,
    flexBasis: 'auto',
    flexGrow: 0,
    flexShrink: 0,
  },
  courseHeaderMark: {
    borderColor: `color-mix(in srgb, ${colors.success} 30%, ${colors.border})`,
    borderRadius: '.7rem',
    borderStyle: 'solid',
    borderWidth: 1,
    paddingBlock: '.25rem',
    paddingInline: '.25rem',
    placeItems: 'center',
    backgroundColor: `color-mix(in srgb, ${colors.success} 8%, ${colors.surface})`,
    color: colors.success,
    display: {
      default: 'grid',
      [media.narrow]: 'none',
    },
    flexBasis: 'auto',
    flexGrow: 0,
    flexShrink: 0,
    fontSize: '0.62rem',
    fontWeight: 750,
    justifyContent: 'center',
    letterSpacing: '.02em',
    textAlign: 'center',
    height: '2.35rem',
    width: '2.35rem',
  },
  courseHeaderCopy: {
    gap: '.4rem',
    display: 'grid',
    minWidth: 0,
  },
  courseHeaderTitle: {
    margin: 0,
    overflow: 'hidden',
    fontSize: {
      default: 'clamp(1.25rem, 2.25vw, 1.75rem)',
      [media.mobile]: '1.1rem',
    },
    fontWeight: 650,
    letterSpacing: '-0.035em',
    lineHeight: 1.15,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '38rem',
    minWidth: 0,
  },
  courseHeaderProgress: {
    gap: '.5rem',
    alignItems: 'center',
    color: colors.textSecondary,
    display: 'flex',
    fontSize: typography.sizeXs,
    fontVariantNumeric: 'tabular-nums',
  },
  courseHeaderProgressTrack: {
    borderRadius: '999px',
    overflow: 'hidden',
    backgroundColor: colors.surfaceHover,
    display: {
      default: 'inline-block',
      [media.narrow]: 'none',
    },
    height: '.25rem',
    width: {
      default: '6rem',
      [media.mobile]: '3.5rem',
    },
  },
  courseHeaderProgressFill: (width: string) => ({
    borderRadius: 'inherit',
    backgroundColor: colors.success,
    display: 'block',
    height: '100%',
    width,
  }),
  courseWorkspaceTabs: {
    borderColor: colors.border,
    borderRadius: layout.radius,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingBlock: '.25rem',
    paddingInline: '.25rem',
    backdropFilter: 'blur(1rem)',
    backgroundColor: `color-mix(in srgb, ${colors.surface} 93%, transparent)`,
    boxShadow: effects.shadow,
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'flex-start',
    position: 'sticky',
    scrollbarWidth: 'none',
    zIndex: 8,
    height: 'auto',
    overflowX: 'auto',
    top: {
      default: '4.35rem',
      [media.mobile]: '3.9rem',
    },
    width: {
      default: '100%',
      [media.mobile]: 'calc(100vw - 2rem)',
    },
  },
  courseWorkspaceTab: {
    gap: '.45rem',
    paddingInline: {
      default: '.8rem',
      [media.mobile]: '.65rem',
    },
    fontSize: '.75rem',
    minHeight: '2.25rem',
  },
  courseWorkspacePanel: {
    outline: 'none',
    marginTop: '1rem',
  },
  coursePracticeDisclosure: {
    borderColor: colors.border,
    borderRadius: '.75rem',
    borderStyle: 'solid',
    borderWidth: 1,
    marginBlock: 0,
    marginInline: 0,
    backgroundColor: colors.surface,
    marginTop: '.85rem',
  },
  coursePracticeDisclosureSummary: {
    gap: '1rem',
    listStyle: 'none',
    paddingBlock: '0.9rem',
    paddingInline: '1rem',
    cursor: 'pointer',
    display: 'flex',
    fontSize: '0.75rem',
    fontWeight: 600,
    justifyContent: 'space-between',
  },
  coursePracticeDisclosureStatus: {
    color: colors.textSecondary,
    fontSize: typography.sizeXs,
    fontWeight: 500,
  },
  courseLoading: {
    marginBlock: 0,
    marginInline: 0,
    paddingBlock: '2rem',
    paddingInline: '2rem',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  courseEmpty: {
    marginBlock: '2rem',
    marginInline: 'auto',
    textAlign: 'center',
    maxWidth: '38rem',
  },
  appErrorActions: {
    gap: '.5rem',
    display: 'flex',
    flexWrap: 'wrap',
    marginTop: '1.25rem',
  },
});
