import * as stylex from '@stylexjs/stylex';
import { media } from '@/styles/constants.stylex';
import { colors, layout, spacing, typography } from '@/styles/tokens.stylex';

export const conversationRailStyles = stylex.create({
  askHistory: {
    gap: '0.2rem',
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    borderTopColor: colors.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    marginTop: '0.15rem',
    minHeight: 0,
    overflowY: 'auto',
    paddingTop: '0.75rem',
  },
  askHistoryEmpty: {
    padding: spacing.md,
    textAlign: 'center',
  },
  askHistoryError: {
    padding: spacing.md,
    gap: spacing.sm,
    alignItems: 'center',
    color: colors.danger,
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'center',
  },
  askSidebarHeading: {
    paddingBlock: spacing.xs,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  askSidebarSectionTitle: {
    gap: spacing.xs,
    alignItems: 'center',
    color: colors.textSecondary,
    display: 'flex',
  },
  askSidebarTitle: {
    margin: 0,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
  },
  askSidebarCount: {
    color: colors.textSecondary,
    fontSize: typography.sizeXs,
  },
  askHistorySearch: {
    borderColor: { default: colors.border, ':focus-within': colors.borderLight },
    borderRadius: '0.55rem',
    borderStyle: 'solid',
    borderWidth: 1,
    gap: spacing.xs,
    paddingBlock: '0.45rem',
    paddingInline: '0.65rem',
    alignItems: 'center',
    backgroundColor: colors.surfaceRaised,
    boxSizing: 'border-box',
    color: colors.textSecondary,
    display: 'flex',
    position: 'relative',
    width: '100%',
  },
  searchIcon: {
    color: colors.textSecondary,
    flexShrink: 0,
  },
  searchInput: {
    padding: 0,
    borderStyle: 'none',
    borderWidth: 0,
    outline: 'none',
    backgroundColor: 'transparent',
    color: colors.textPrimary,
    fontFamily: 'inherit',
    fontSize: typography.sizeSm,
    width: '100%',
  },
  askSidebar: {
    padding: {
      default: '0.125rem 1.25rem 0.75rem 0.5rem',
      [media.tablet]: '0.75rem',
    },
    borderColor: colors.border,
    borderRadius: {
      default: 0,
      [media.tablet]: '0.8rem',
    },
    borderStyle: 'solid',
    borderWidth: {
      default: 0,
      [media.tablet]: 1,
    },
    gap: '1rem',
    backgroundColor: {
      default: 'transparent',
      [media.tablet]: colors.surface,
    },
    boxSizing: 'border-box',
    display: {
      default: 'flex',
      [media.tablet]: 'none',
    },
    flexDirection: 'column',
    position: {
      default: 'sticky',
      [media.tablet]: 'static',
    },
    borderRightColor: colors.border,
    borderRightStyle: 'solid',
    borderRightWidth: {
      default: 1,
      [media.tablet]: 0,
    },
    height: {
      default: 'calc(100svh - 6.75rem)',
      [media.tablet]: 'auto',
    },
    minWidth: 0,
    top: '1.25rem',
  },
  askSidebarMobileOpen: {
    display: 'flex',
  },
  askNew: {
    borderColor: { default: colors.borderLight, ':hover': colors.textSecondary },
    borderRadius: '0.7rem',
    borderStyle: 'solid',
    borderWidth: 1,
    gap: '0.6rem',
    paddingBlock: '0.65rem',
    paddingInline: '0.8rem',
    textDecoration: 'none',
    alignItems: 'center',
    backgroundColor: { default: colors.surfaceRaised, ':hover': colors.surfaceHover },
    color: colors.textPrimary,
    display: 'flex',
    fontSize: typography.sizeSm,
    fontWeight: 550,
    justifyContent: 'flex-start',
    transform: {
      default: 'none',
      ':hover': 'translateY(-1px)',
    },
    transitionDuration: '160ms',
    transitionProperty: 'background-color, border-color, transform',
    minHeight: '2.75rem',
  },
  askRail: {
    padding: {
      default: '1.25rem 1.5rem 1.25rem 0',
      [media.tablet]: '0.75rem 1rem 0',
    },
    minWidth: 0,
  },
  askHistoryToggle: {
    padding: spacing.sm,
    borderColor: colors.border,
    borderRadius: layout.radius,
    borderStyle: 'solid',
    borderWidth: 1,
    alignItems: 'center',
    backgroundColor: colors.surfaceRaised,
    color: colors.textPrimary,
    cursor: 'pointer',
    display: {
      default: 'none',
      [media.tablet]: 'flex',
    },
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    width: '100%',
  },
});
