import {
  Archive,
  ArrowDown,
  ArrowRight,
  ArrowUpRight,
  Award,
  Bell,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  Circle,
  CircleDot,
  Clock3,
  Cloud,
  Cpu,
  Database,
  Download,
  Eye,
  EyeOff,
  File,
  FileDiff,
  Folder,
  FolderOpen,
  Hourglass,
  KeyRound,
  List,
  MessageCircle,
  MailOpen,
  Megaphone,
  Minus,
  Moon,
  Palette,
  Presentation,
  Paperclip,
  PieChart,
  Plug,
  RotateCcw,
  Search,
  Settings2,
  Signpost,
  SlidersHorizontal,
  Sparkles,
  SquareArrowOutUpRight,
  Sun,
  Trash2,
  TreePine,
  X,
  type LucideIcon,
} from 'lucide-react';
import * as stylex from '@stylexjs/stylex';
import type { StyleXStyles } from '@stylexjs/stylex';

const ICONS = {
  'arrow-counterclockwise': RotateCcw,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  archive: Archive,
  award: Award,
  bell: Bell,
  'box-arrow-up-right': SquareArrowOutUpRight,
  'check-circle': CheckCircle,
  'check-lg': Check,
  check2: Check,
  'check2-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-half': CircleDot,
  circle: Circle,
  'circle-fill': CircleDot,
  clock: Clock3,
  'clock-history': Clock3,
  cloud: Cloud,
  cpu: Cpu,
  database: Database,
  download: Download,
  discord: MessageCircle,
  eye: Eye,
  'eye-slash': EyeOff,
  exclamation: CircleHelp,
  'exclamation-lg': CircleHelp,
  'file-diff': FileDiff,
  'file-earmark': File,
  'folder-fill': Folder,
  'folder2-open': FolderOpen,
  'hourglass-split': Hourglass,
  key: KeyRound,
  'key-fill': KeyRound,
  list: List,
  'mail-open': MailOpen,
  megaphone: Megaphone,
  'moon-stars-fill': Moon,
  palette2: Palette,
  paperclip: Paperclip,
  presentation: Presentation,
  'pie-chart': PieChart,
  plug: Plug,
  'question-circle': CircleHelp,
  dash: Minus,
  'record-circle-fill': CircleDot,
  search: Search,
  settings: Settings2,
  'signpost-split': Signpost,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  'skip-forward': ArrowRight,
  sun: Sun,
  trash3: Trash2,
  'tree-fill': TreePine,
  'x-lg': X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

const styles = stylex.create({
  icon: {
    strokeWidth: 1.8,
    blockSize: '1em',
    color: 'currentColor',
    flexShrink: 0,
    inlineSize: '1em',
    verticalAlign: 'middle',
  },
});

export interface IconProps {
  name: string;
  style?: StyleXStyles;
  'aria-hidden'?: boolean | 'true' | 'false';
}

export function Icon({ name, style, ...props }: IconProps) {
  // SAFETY: unknown runtime icon names fall back to CircleHelp below.
  const IconComponent = ICONS[name as IconName] ?? CircleHelp;
  return <IconComponent {...props} {...stylex.props(styles.icon, style)} />;
}
