import * as stylex from '@stylexjs/stylex';
import { media } from './constants.stylex';
import { colors, effects, layout, typography } from './tokens.stylex';

export const styles = stylex.create({
  body: {
    WebkitFontSmoothing: 'antialiased',
    backgroundColor: colors.background,
    color: colors.textPrimary,
    fontFamily: "Inter, 'Helvetica Neue', Arial, sans-serif",
    fontSize: typography.sizeBase,
    lineHeight: layout.bodyLeading,
  },
  main: {
    marginInline: 'auto',
    paddingInline: { default: layout.gutter, [media.mobile]: '1rem' },
    boxSizing: 'border-box',
    paddingBlockEnd: { default: '4rem', [media.mobile]: '3rem' },
    paddingBlockStart: { default: '2.5rem', [media.mobile]: '1.5rem' },
    maxWidth: layout.rail,
    minHeight: 'calc(100vh - 5.25rem)',
    width: '100%',
  },
  sessionMain: {
    paddingInline: 0,
    paddingBlockEnd: 0,
    paddingBlockStart: 0,
    maxWidth: 'none',
    minHeight: '100dvh',
  },
  skipLink: {
    borderColor: colors.borderLight,
    borderRadius: layout.radius,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingBlock: '0.5rem',
    paddingInline: '0.75rem',
    backgroundColor: colors.surfaceRaised,
    color: colors.textPrimary,
    position: 'fixed',
    transform: { default: 'translateY(-180%)', ':focus': 'translateY(0)' },
    transitionProperty: 'transform',
    zIndex: 1000,
    left: '0.75rem',
    top: '0.5rem',
  },
  navbar: {
    paddingBlock: '0.75rem',
    backdropFilter: 'blur(1.125rem)',
    backgroundColor: colors.background,
    borderBlockEndColor: colors.border,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
    position: 'sticky',
    zIndex: 20,
    top: 0,
  },
  sessionNavbar: {
    display: 'none',
  },
  container: {
    gap: { default: '1.5rem', [media.tablet]: '0.5rem 0.75rem' },
    marginInline: 'auto',
    paddingInline: { default: layout.gutter, [media.mobile]: '1rem' },
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    maxWidth: layout.rail,
    minHeight: '2.75rem',
    width: '100%',
  },
  navBrand: {
    flex: { default: '0 1 auto', [media.tablet]: '1 1 auto' },
    gap: '0.75rem',
    alignItems: 'center',
    display: 'flex',
    minWidth: { default: 'auto', [media.tablet]: 0 },
  },
  logoLink: {
    gap: '0.625rem',
    alignItems: 'center',
    display: 'flex',
    opacity: { default: 1, ':hover': 0.8 },
  },
  logo: {
    gap: '0.35rem',
    alignItems: 'center',
    color: colors.success,
    display: 'inline-flex',
    fontSize: '1rem',
    fontWeight: 650,
    letterSpacing: '-0.025em',
  },
  logoName: {
    color: colors.textPrimary,
    display: { default: 'inline', [media.narrow]: 'none' },
  },
  navLinkCurrent: {
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    color: colors.textPrimary,
    fontWeight: typography.weightSemibold,
  },
  navCurrentView: {
    overflow: 'hidden',
    borderInlineStartColor: { default: 'transparent', [media.tablet]: colors.border },
    borderInlineStartStyle: { default: 'solid', [media.tablet]: 'solid' },
    borderInlineStartWidth: { default: 0, [media.tablet]: 1 },
    display: { default: 'none', [media.tablet]: 'block' },
    fontSize: typography.sizeMd,
    fontWeight: 600,
    lineHeight: 1.2,
    paddingInlineStart: { default: 0, [media.tablet]: '0.75rem' },
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: { default: 'none', [media.tablet]: 'min(13rem, 32vw)', [media.narrow]: '45vw' },
    minWidth: 0,
  },
  navLinks: {
    padding: { default: null, [media.tablet]: '0.5rem' },
    gap: '0.25rem',
    listStyle: 'none',
    alignItems: 'center',
    backgroundColor: { default: null, [media.tablet]: colors.surface },
    borderBlockEndColor: { default: null, [media.tablet]: colors.border },
    borderBlockEndStyle: { default: null, [media.tablet]: 'solid' },
    borderBlockEndWidth: { default: null, [media.tablet]: 1 },
    boxShadow: { default: null, [media.tablet]: effects.shadowLarge },
    display: { default: 'flex', [media.desktop]: 'flex', [media.tablet]: 'none' },
    gridTemplateColumns: { default: null, [media.tablet]: 'repeat(auto-fit, minmax(8.5rem, 1fr))' },
    marginInlineStart: 'auto',
    position: { default: 'static', [media.tablet]: 'absolute' },
    left: { default: null, [media.tablet]: 0 },
    right: { default: null, [media.tablet]: 0 },
    top: { default: null, [media.tablet]: '100%' },
    width: { default: 'auto', [media.tablet]: '100%' },
  },
  navLink: {
    borderColor: { default: 'transparent', ':hover': colors.border },
    borderRadius: layout.radius,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingBlock: '0.35rem',
    paddingInline: '0.7rem',
    alignItems: 'center',
    backgroundColor: { default: 'transparent', ':hover': colors.surfaceRaised },
    boxSizing: 'border-box',
    color: { default: colors.textSecondary, ':hover': colors.textPrimary },
    display: 'inline-flex',
    fontSize: '0.8125rem',
    fontWeight: typography.weightMedium,
    justifyContent: { default: null, [media.tablet]: 'center' },
    lineHeight: 1.25,
    transitionProperty: 'background-color, border-color, color',
    height: '2.5rem',
    minHeight: { default: '2.5rem', [media.tablet]: '2.5rem' },
    width: { default: null, [media.tablet]: '100%' },
  },
  navUtility: {
    gap: '0.5rem',
    alignItems: 'center',
    display: { default: 'flex', [media.tablet]: 'grid' },
    flexBasis: 'auto',
    flexGrow: 0,
    flexShrink: 0,
    gridTemplateColumns: { default: null, [media.tablet]: 'max-content max-content' },
    marginInlineStart: 'auto',
    maxWidth: '100%',
    minWidth: 0,
    width: { default: 'auto', [media.tablet]: 'max-content' },
  },
  navSearch: {
    padding: { default: null, [media.narrow]: 0 },
    borderColor: { default: colors.border, ':hover': colors.borderLight },
    borderRadius: '0.55rem',
    borderStyle: 'solid',
    borderWidth: 1,
    gap: '0.5rem',
    overflow: 'hidden',
    paddingBlock: '0.45rem',
    paddingInline: '0.6rem',
    textDecoration: 'none',
    alignItems: 'center',
    backgroundColor: { default: colors.surfaceRaised, ':hover': colors.surfaceHover },
    color: { default: colors.textSecondary, ':hover': colors.textPrimary },
    display: 'flex',
    fontSize: typography.sizeXs,
    justifyContent: { default: null, [media.narrow]: 'center' },
    lineHeight: 1.55,
    transitionProperty: 'background-color, border-color, color',
    height: '2.5rem',
    maxWidth: { default: '18vw', [media.tablet]: 'none' },
    minHeight: '2.5rem',
    minWidth: { default: 'min(10.5rem, 100%)', [media.tablet]: 'auto' },
    width: { default: null, [media.narrow]: '2.5rem' },
  },
  navSearchLabel: {
    overflow: 'hidden',
    display: { default: 'inline', [media.narrow]: 'none' },
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  navMenuButton: {
    padding: 0,
    borderColor: colors.border,
    borderRadius: '0.55rem',
    borderStyle: 'solid',
    borderWidth: 1,
    alignItems: 'center',
    backgroundColor: { default: colors.surfaceRaised, ':hover': colors.surfaceHover },
    color: { default: colors.textSecondary, ':hover': colors.textPrimary },
    cursor: 'pointer',
    display: { default: 'none', [media.tablet]: 'grid' },
    fontSize: '1.125rem',
    justifyContent: 'center',
    minHeight: '2.5rem',
    minWidth: '2.5rem',
  },
  orbit: {
    position: 'relative',
  },
  orbitPanel: {
    padding: '0.55rem',
    borderColor: colors.borderLight,
    borderRadius: '1.05rem',
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: colors.surface,
    boxShadow: effects.shadowLarge,
    display: { default: 'block', [media.tablet]: 'none' },
    opacity: 0,
    pointerEvents: 'none',
    position: 'absolute',
    transform: 'translateX(-50%) translateY(-0.35rem) scale(0.985)',
    transformOrigin: '50% 0',
    transitionProperty: 'opacity, transform',
    zIndex: 2,
    left: '50%',
    top: 'calc(100% - 0.0625rem)',
    width: 'min(23rem, calc(100vw - 2rem))',
  },
  orbitList: {
    margin: 0,
    padding: 0,
    gap: '0.2rem',
    listStyle: 'none',
    overscrollBehavior: 'contain',
    display: 'grid',
    maxHeight: 'min(25rem, calc(100vh - 6rem))',
    overflowY: 'auto',
  },
  orbitLink: {
    borderColor: { default: 'transparent', ':hover': colors.border },
    borderRadius: '0.7rem',
    borderStyle: 'solid',
    borderWidth: 1,
    gap: '0.65rem',
    paddingBlock: '0.5rem',
    paddingInline: '0.65rem',
    textDecoration: 'none',
    alignItems: 'center',
    backgroundColor: { default: 'transparent', ':hover': colors.surfaceHover },
    color: colors.textPrimary,
    display: 'grid',
    gridTemplateColumns: '1.75rem minmax(0, 1fr) auto',
    opacity: 0,
    transform: 'translateY(-0.3rem)',
    transitionProperty: 'background-color, border-color, opacity, transform',
    minHeight: '2.75rem',
  },
  orbitIndex: {
    color: colors.textSecondary,
    fontFamily: 'Roboto Mono, monospace',
    fontSize: typography.sizeXs,
  },
  orbitName: { fontWeight: 580, overflowWrap: 'anywhere', minWidth: 0 },
  orbitStatus: {
    margin: 0,
    paddingBlock: '0.7rem',
    paddingInline: '0.65rem',
    color: colors.textSecondary,
    fontSize: typography.sizeXs,
  },
});
