// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package queries

import (
	"context"
)

const addCourse = `-- name: AddCourse :exec
INSERT INTO app.courses(id,name,webdav_folder) VALUES($1,$2,$3)
`

type AddCourseParams struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	WebdavFolder string `json:"webdav_folder"`
}

func (q *Queries) AddCourse(ctx context.Context, arg AddCourseParams) error {
	_, err := q.db.Exec(ctx, addCourse, arg.ID, arg.Name, arg.WebdavFolder)
	return err
}

const course = `-- name: Course :one
SELECT id,name,webdav_folder,sort_order,hidden,short_name FROM app.courses WHERE id=$1
`

func (q *Queries) Course(ctx context.Context, id int64) (AppCourse, error) {
	row := q.db.QueryRow(ctx, course, id)
	var i AppCourse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebdavFolder,
		&i.SortOrder,
		&i.Hidden,
		&i.ShortName,
	)
	return i, err
}

const courseCoverage = `-- name: CourseCoverage :many
SELECT course_id,payload_json FROM read_model.course_coverage ORDER BY course_id
`

type CourseCoverageRow struct {
	CourseID    int64  `json:"course_id"`
	PayloadJson string `json:"payload_json"`
}

func (q *Queries) CourseCoverage(ctx context.Context) ([]CourseCoverageRow, error) {
	rows, err := q.db.Query(ctx, courseCoverage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseCoverageRow{}
	for rows.Next() {
		var i CourseCoverageRow
		if err := rows.Scan(&i.CourseID, &i.PayloadJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hideCourse = `-- name: HideCourse :execrows
UPDATE app.courses SET hidden=$2 WHERE id=$1
`

type HideCourseParams struct {
	ID     int64 `json:"id"`
	Hidden int64 `json:"hidden"`
}

func (q *Queries) HideCourse(ctx context.Context, arg HideCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, hideCourse, arg.ID, arg.Hidden)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCourses = `-- name: ListCourses :many
SELECT id,name,webdav_folder,sort_order,hidden,short_name FROM app.courses
WHERE hidden=0 OR $1::boolean ORDER BY sort_order,id
`

func (q *Queries) ListCourses(ctx context.Context, includeHidden bool) ([]AppCourse, error) {
	rows, err := q.db.Query(ctx, listCourses, includeHidden)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppCourse{}
	for rows.Next() {
		var i AppCourse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebdavFolder,
			&i.SortOrder,
			&i.Hidden,
			&i.ShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderCourse = `-- name: OrderCourse :exec
UPDATE app.courses SET sort_order=$2 WHERE id=$1
`

type OrderCourseParams struct {
	ID        int64  `json:"id"`
	SortOrder *int64 `json:"sort_order"`
}

func (q *Queries) OrderCourse(ctx context.Context, arg OrderCourseParams) error {
	_, err := q.db.Exec(ctx, orderCourse, arg.ID, arg.SortOrder)
	return err
}

const recentMaterials = `-- name: RecentMaterials :many
SELECT course_id,payload_json FROM read_model.recent_materials ORDER BY ordinal
`

type RecentMaterialsRow struct {
	CourseID    int64  `json:"course_id"`
	PayloadJson string `json:"payload_json"`
}

func (q *Queries) RecentMaterials(ctx context.Context) ([]RecentMaterialsRow, error) {
	rows, err := q.db.Query(ctx, recentMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentMaterialsRow{}
	for rows.Next() {
		var i RecentMaterialsRow
		if err := rows.Scan(&i.CourseID, &i.PayloadJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCourse = `-- name: RenameCourse :execrows
UPDATE app.courses SET name=$2 WHERE id=$1
`

type RenameCourseParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RenameCourse(ctx context.Context, arg RenameCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameCourse, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStudyLevel = `-- name: SetStudyLevel :exec
INSERT INTO app.file_study(course_id,file_path,level,last_updated) VALUES($1,$2,$3,$4)
ON CONFLICT(course_id,file_path) DO UPDATE SET level=excluded.level,last_updated=excluded.last_updated
`

type SetStudyLevelParams struct {
	CourseID    int64   `json:"course_id"`
	FilePath    string  `json:"file_path"`
	Level       int64   `json:"level"`
	LastUpdated *string `json:"last_updated"`
}

func (q *Queries) SetStudyLevel(ctx context.Context, arg SetStudyLevelParams) error {
	_, err := q.db.Exec(ctx, setStudyLevel,
		arg.CourseID,
		arg.FilePath,
		arg.Level,
		arg.LastUpdated,
	)
	return err
}

const studyLevels = `-- name: StudyLevels :many
SELECT course_id,file_path,level FROM app.file_study ORDER BY course_id,file_path
`

type StudyLevelsRow struct {
	CourseID int64  `json:"course_id"`
	FilePath string `json:"file_path"`
	Level    int64  `json:"level"`
}

func (q *Queries) StudyLevels(ctx context.Context) ([]StudyLevelsRow, error) {
	rows, err := q.db.Query(ctx, studyLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudyLevelsRow{}
	for rows.Next() {
		var i StudyLevelsRow
		if err := rows.Scan(&i.CourseID, &i.FilePath, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
