// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materials.sql

package queries

import (
	"context"
)

const externalMaterials = `-- name: ExternalMaterials :many
SELECT d.id, d.course_id, d.course_name, d.course_short_name, d.source_path, d.source_origin, d.normalized_path, d.source_url, d.display_name, d.source_hash, d.source_fingerprint, d.source_etag, d.content_hash_verified, d.mime_type, d.response_mime_type, d.document_kind, d.academic_year, d.source_modified_at, d.is_current, d.status, d.page_count, d.source_size_bytes, d.character_count, d.word_count, d.reading_minutes, d.complexity_score, d.complexity_label, d.language_hint, d.extractor_name, d.extractor_version, d.indexed_at, d.error, d.diagnostic_reason, d.warnings_json,m.material_type,m.source_label FROM knowledge.documents d
LEFT JOIN app.external_material_metadata m ON m.course_id=d.course_id AND m.source_path=d.source_path
WHERE d.course_id=$1 AND d.source_origin='external' AND d.is_current=1 ORDER BY d.display_name,d.id
`

type ExternalMaterialsRow struct {
	ID                  string  `json:"id"`
	CourseID            int64   `json:"course_id"`
	CourseName          string  `json:"course_name"`
	CourseShortName     *string `json:"course_short_name"`
	SourcePath          string  `json:"source_path"`
	SourceOrigin        string  `json:"source_origin"`
	NormalizedPath      string  `json:"normalized_path"`
	SourceUrl           *string `json:"source_url"`
	DisplayName         string  `json:"display_name"`
	SourceHash          string  `json:"source_hash"`
	SourceFingerprint   string  `json:"source_fingerprint"`
	SourceEtag          *string `json:"source_etag"`
	ContentHashVerified int64   `json:"content_hash_verified"`
	MimeType            *string `json:"mime_type"`
	ResponseMimeType    *string `json:"response_mime_type"`
	DocumentKind        string  `json:"document_kind"`
	AcademicYear        *string `json:"academic_year"`
	SourceModifiedAt    *string `json:"source_modified_at"`
	IsCurrent           int64   `json:"is_current"`
	Status              string  `json:"status"`
	PageCount           *int64  `json:"page_count"`
	SourceSizeBytes     *int64  `json:"source_size_bytes"`
	CharacterCount      *int64  `json:"character_count"`
	WordCount           *int64  `json:"word_count"`
	ReadingMinutes      *int64  `json:"reading_minutes"`
	ComplexityScore     *int64  `json:"complexity_score"`
	ComplexityLabel     *string `json:"complexity_label"`
	LanguageHint        *string `json:"language_hint"`
	ExtractorName       *string `json:"extractor_name"`
	ExtractorVersion    *string `json:"extractor_version"`
	IndexedAt           *string `json:"indexed_at"`
	Error               *string `json:"error"`
	DiagnosticReason    *string `json:"diagnostic_reason"`
	WarningsJson        string  `json:"warnings_json"`
	MaterialType        *string `json:"material_type"`
	SourceLabel         *string `json:"source_label"`
}

func (q *Queries) ExternalMaterials(ctx context.Context, courseID int64) ([]ExternalMaterialsRow, error) {
	rows, err := q.db.Query(ctx, externalMaterials, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalMaterialsRow{}
	for rows.Next() {
		var i ExternalMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.CourseName,
			&i.CourseShortName,
			&i.SourcePath,
			&i.SourceOrigin,
			&i.NormalizedPath,
			&i.SourceUrl,
			&i.DisplayName,
			&i.SourceHash,
			&i.SourceFingerprint,
			&i.SourceEtag,
			&i.ContentHashVerified,
			&i.MimeType,
			&i.ResponseMimeType,
			&i.DocumentKind,
			&i.AcademicYear,
			&i.SourceModifiedAt,
			&i.IsCurrent,
			&i.Status,
			&i.PageCount,
			&i.SourceSizeBytes,
			&i.CharacterCount,
			&i.WordCount,
			&i.ReadingMinutes,
			&i.ComplexityScore,
			&i.ComplexityLabel,
			&i.LanguageHint,
			&i.ExtractorName,
			&i.ExtractorVersion,
			&i.IndexedAt,
			&i.Error,
			&i.DiagnosticReason,
			&i.WarningsJson,
			&i.MaterialType,
			&i.SourceLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const indexChunkSearch = `-- name: IndexChunkSearch :exec
INSERT INTO knowledge.chunks_fts(chunk_id,text,normalized_text,heading,display_name,source_path,course_name)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type IndexChunkSearchParams struct {
	ChunkID        string  `json:"chunk_id"`
	Text           *string `json:"text"`
	NormalizedText *string `json:"normalized_text"`
	Heading        *string `json:"heading"`
	DisplayName    *string `json:"display_name"`
	SourcePath     *string `json:"source_path"`
	CourseName     *string `json:"course_name"`
}

func (q *Queries) IndexChunkSearch(ctx context.Context, arg IndexChunkSearchParams) error {
	_, err := q.db.Exec(ctx, indexChunkSearch,
		arg.ChunkID,
		arg.Text,
		arg.NormalizedText,
		arg.Heading,
		arg.DisplayName,
		arg.SourcePath,
		arg.CourseName,
	)
	return err
}

const indexDocument = `-- name: IndexDocument :one
SELECT id, course_id, course_name, course_short_name, source_path, source_origin, normalized_path, source_url, display_name, source_hash, source_fingerprint, source_etag, content_hash_verified, mime_type, response_mime_type, document_kind, academic_year, source_modified_at, is_current, status, page_count, source_size_bytes, character_count, word_count, reading_minutes, complexity_score, complexity_label, language_hint, extractor_name, extractor_version, indexed_at, error, diagnostic_reason, warnings_json FROM knowledge.documents WHERE id=$1 AND is_current=1
`

func (q *Queries) IndexDocument(ctx context.Context, id string) (KnowledgeDocument, error) {
	row := q.db.QueryRow(ctx, indexDocument, id)
	var i KnowledgeDocument
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CourseName,
		&i.CourseShortName,
		&i.SourcePath,
		&i.SourceOrigin,
		&i.NormalizedPath,
		&i.SourceUrl,
		&i.DisplayName,
		&i.SourceHash,
		&i.SourceFingerprint,
		&i.SourceEtag,
		&i.ContentHashVerified,
		&i.MimeType,
		&i.ResponseMimeType,
		&i.DocumentKind,
		&i.AcademicYear,
		&i.SourceModifiedAt,
		&i.IsCurrent,
		&i.Status,
		&i.PageCount,
		&i.SourceSizeBytes,
		&i.CharacterCount,
		&i.WordCount,
		&i.ReadingMinutes,
		&i.ComplexityScore,
		&i.ComplexityLabel,
		&i.LanguageHint,
		&i.ExtractorName,
		&i.ExtractorVersion,
		&i.IndexedAt,
		&i.Error,
		&i.DiagnosticReason,
		&i.WarningsJson,
	)
	return i, err
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO knowledge.chunks(id,document_id,ordinal,locator_type,locator_start,locator_end,heading,text,normalized_text,content_hash,metadata_json)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type InsertChunkParams struct {
	ID             string  `json:"id"`
	DocumentID     string  `json:"document_id"`
	Ordinal        int64   `json:"ordinal"`
	LocatorType    string  `json:"locator_type"`
	LocatorStart   *string `json:"locator_start"`
	LocatorEnd     *string `json:"locator_end"`
	Heading        *string `json:"heading"`
	Text           string  `json:"text"`
	NormalizedText string  `json:"normalized_text"`
	ContentHash    string  `json:"content_hash"`
	MetadataJson   string  `json:"metadata_json"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.Exec(ctx, insertChunk,
		arg.ID,
		arg.DocumentID,
		arg.Ordinal,
		arg.LocatorType,
		arg.LocatorStart,
		arg.LocatorEnd,
		arg.Heading,
		arg.Text,
		arg.NormalizedText,
		arg.ContentHash,
		arg.MetadataJson,
	)
	return err
}

const markIndexed = `-- name: MarkIndexed :exec
UPDATE knowledge.documents SET status='ready',page_count=$2,character_count=$3,word_count=$4,reading_minutes=$5,
extractor_name='tree-parser',extractor_version='1',indexed_at=$6,error=NULL,warnings_json=$7,complexity_score=$8,complexity_label=$9 WHERE id=$1
`

type MarkIndexedParams struct {
	ID              string  `json:"id"`
	PageCount       *int64  `json:"page_count"`
	CharacterCount  *int64  `json:"character_count"`
	WordCount       *int64  `json:"word_count"`
	ReadingMinutes  *int64  `json:"reading_minutes"`
	IndexedAt       *string `json:"indexed_at"`
	WarningsJson    string  `json:"warnings_json"`
	ComplexityScore *int64  `json:"complexity_score"`
	ComplexityLabel *string `json:"complexity_label"`
}

func (q *Queries) MarkIndexed(ctx context.Context, arg MarkIndexedParams) error {
	_, err := q.db.Exec(ctx, markIndexed,
		arg.ID,
		arg.PageCount,
		arg.CharacterCount,
		arg.WordCount,
		arg.ReadingMinutes,
		arg.IndexedAt,
		arg.WarningsJson,
		arg.ComplexityScore,
		arg.ComplexityLabel,
	)
	return err
}

const material = `-- name: Material :one
SELECT d.id, d.course_id, d.course_name, d.course_short_name, d.source_path, d.source_origin, d.normalized_path, d.source_url, d.display_name, d.source_hash, d.source_fingerprint, d.source_etag, d.content_hash_verified, d.mime_type, d.response_mime_type, d.document_kind, d.academic_year, d.source_modified_at, d.is_current, d.status, d.page_count, d.source_size_bytes, d.character_count, d.word_count, d.reading_minutes, d.complexity_score, d.complexity_label, d.language_hint, d.extractor_name, d.extractor_version, d.indexed_at, d.error, d.diagnostic_reason, d.warnings_json,m.material_type,m.source_label FROM knowledge.documents d
LEFT JOIN app.external_material_metadata m ON m.course_id=d.course_id AND m.source_path=d.source_path
WHERE d.course_id=$1 AND d.id=$2 AND d.source_origin='external' AND d.is_current=1
`

type MaterialParams struct {
	CourseID int64  `json:"course_id"`
	ID       string `json:"id"`
}

type MaterialRow struct {
	ID                  string  `json:"id"`
	CourseID            int64   `json:"course_id"`
	CourseName          string  `json:"course_name"`
	CourseShortName     *string `json:"course_short_name"`
	SourcePath          string  `json:"source_path"`
	SourceOrigin        string  `json:"source_origin"`
	NormalizedPath      string  `json:"normalized_path"`
	SourceUrl           *string `json:"source_url"`
	DisplayName         string  `json:"display_name"`
	SourceHash          string  `json:"source_hash"`
	SourceFingerprint   string  `json:"source_fingerprint"`
	SourceEtag          *string `json:"source_etag"`
	ContentHashVerified int64   `json:"content_hash_verified"`
	MimeType            *string `json:"mime_type"`
	ResponseMimeType    *string `json:"response_mime_type"`
	DocumentKind        string  `json:"document_kind"`
	AcademicYear        *string `json:"academic_year"`
	SourceModifiedAt    *string `json:"source_modified_at"`
	IsCurrent           int64   `json:"is_current"`
	Status              string  `json:"status"`
	PageCount           *int64  `json:"page_count"`
	SourceSizeBytes     *int64  `json:"source_size_bytes"`
	CharacterCount      *int64  `json:"character_count"`
	WordCount           *int64  `json:"word_count"`
	ReadingMinutes      *int64  `json:"reading_minutes"`
	ComplexityScore     *int64  `json:"complexity_score"`
	ComplexityLabel     *string `json:"complexity_label"`
	LanguageHint        *string `json:"language_hint"`
	ExtractorName       *string `json:"extractor_name"`
	ExtractorVersion    *string `json:"extractor_version"`
	IndexedAt           *string `json:"indexed_at"`
	Error               *string `json:"error"`
	DiagnosticReason    *string `json:"diagnostic_reason"`
	WarningsJson        string  `json:"warnings_json"`
	MaterialType        *string `json:"material_type"`
	SourceLabel         *string `json:"source_label"`
}

func (q *Queries) Material(ctx context.Context, arg MaterialParams) (MaterialRow, error) {
	row := q.db.QueryRow(ctx, material, arg.CourseID, arg.ID)
	var i MaterialRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CourseName,
		&i.CourseShortName,
		&i.SourcePath,
		&i.SourceOrigin,
		&i.NormalizedPath,
		&i.SourceUrl,
		&i.DisplayName,
		&i.SourceHash,
		&i.SourceFingerprint,
		&i.SourceEtag,
		&i.ContentHashVerified,
		&i.MimeType,
		&i.ResponseMimeType,
		&i.DocumentKind,
		&i.AcademicYear,
		&i.SourceModifiedAt,
		&i.IsCurrent,
		&i.Status,
		&i.PageCount,
		&i.SourceSizeBytes,
		&i.CharacterCount,
		&i.WordCount,
		&i.ReadingMinutes,
		&i.ComplexityScore,
		&i.ComplexityLabel,
		&i.LanguageHint,
		&i.ExtractorName,
		&i.ExtractorVersion,
		&i.IndexedAt,
		&i.Error,
		&i.DiagnosticReason,
		&i.WarningsJson,
		&i.MaterialType,
		&i.SourceLabel,
	)
	return i, err
}

const materialMetadata = `-- name: MaterialMetadata :exec
INSERT INTO app.external_material_metadata(course_id,source_path,material_type,source_label,notes)
VALUES($1,$2,$3,'Browser upload','')
ON CONFLICT(course_id,source_path) DO UPDATE SET material_type=excluded.material_type
`

type MaterialMetadataParams struct {
	CourseID     int64  `json:"course_id"`
	SourcePath   string `json:"source_path"`
	MaterialType string `json:"material_type"`
}

func (q *Queries) MaterialMetadata(ctx context.Context, arg MaterialMetadataParams) error {
	_, err := q.db.Exec(ctx, materialMetadata, arg.CourseID, arg.SourcePath, arg.MaterialType)
	return err
}

const observeDocument = `-- name: ObserveDocument :exec
INSERT INTO knowledge.documents(id,course_id,course_name,course_short_name,source_path,normalized_path,display_name,source_hash,mime_type,document_kind,source_size_bytes,status,source_origin,content_hash_verified)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'pending','external',1)
`

type ObserveDocumentParams struct {
	ID              string  `json:"id"`
	CourseID        int64   `json:"course_id"`
	CourseName      string  `json:"course_name"`
	CourseShortName *string `json:"course_short_name"`
	SourcePath      string  `json:"source_path"`
	NormalizedPath  string  `json:"normalized_path"`
	DisplayName     string  `json:"display_name"`
	SourceHash      string  `json:"source_hash"`
	MimeType        *string `json:"mime_type"`
	DocumentKind    string  `json:"document_kind"`
	SourceSizeBytes *int64  `json:"source_size_bytes"`
}

func (q *Queries) ObserveDocument(ctx context.Context, arg ObserveDocumentParams) error {
	_, err := q.db.Exec(ctx, observeDocument,
		arg.ID,
		arg.CourseID,
		arg.CourseName,
		arg.CourseShortName,
		arg.SourcePath,
		arg.NormalizedPath,
		arg.DisplayName,
		arg.SourceHash,
		arg.MimeType,
		arg.DocumentKind,
		arg.SourceSizeBytes,
	)
	return err
}

const replaceChunks = `-- name: ReplaceChunks :exec
DELETE FROM knowledge.chunks WHERE document_id=$1
`

func (q *Queries) ReplaceChunks(ctx context.Context, documentID string) error {
	_, err := q.db.Exec(ctx, replaceChunks, documentID)
	return err
}
