// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: objects.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const documentObject = `-- name: DocumentObject :one
SELECT o.id, o.bucket, o.key, o.version_id, o.sha256, o.bytes, o.media_type, o.created_at,r.logical_path,r.course_id FROM app.document_revisions r JOIN app.objects o ON o.id=r.object_id
WHERE r.document_id=$1 AND r.deleted_at IS NULL
AND (($2::text='' AND EXISTS (
    SELECT 1 FROM knowledge.documents d WHERE d.id=r.document_id AND d.is_current=1 AND d.source_hash=o.sha256
)) OR r.id=$2::text)
ORDER BY r.created_at DESC LIMIT 1
`

type DocumentObjectParams struct {
	DocumentID string `json:"document_id"`
	Revision   string `json:"revision"`
}

type DocumentObjectRow struct {
	ID          string             `json:"id"`
	Bucket      string             `json:"bucket"`
	Key         string             `json:"key"`
	VersionID   string             `json:"version_id"`
	Sha256      string             `json:"sha256"`
	Bytes       int64              `json:"bytes"`
	MediaType   string             `json:"media_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LogicalPath string             `json:"logical_path"`
	CourseID    int64              `json:"course_id"`
}

func (q *Queries) DocumentObject(ctx context.Context, arg DocumentObjectParams) (DocumentObjectRow, error) {
	row := q.db.QueryRow(ctx, documentObject, arg.DocumentID, arg.Revision)
	var i DocumentObjectRow
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.Key,
		&i.VersionID,
		&i.Sha256,
		&i.Bytes,
		&i.MediaType,
		&i.CreatedAt,
		&i.LogicalPath,
		&i.CourseID,
	)
	return i, err
}

const fileObject = `-- name: FileObject :one
SELECT o.id, o.bucket, o.key, o.version_id, o.sha256, o.bytes, o.media_type, o.created_at,r.logical_path,r.course_id FROM app.document_revisions r JOIN app.objects o ON o.id=r.object_id
WHERE r.id=$1 AND r.deleted_at IS NULL AND EXISTS(SELECT 1 FROM app.courses c WHERE c.id=r.course_id AND c.hidden=0)
`

type FileObjectRow struct {
	ID          string             `json:"id"`
	Bucket      string             `json:"bucket"`
	Key         string             `json:"key"`
	VersionID   string             `json:"version_id"`
	Sha256      string             `json:"sha256"`
	Bytes       int64              `json:"bytes"`
	MediaType   string             `json:"media_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LogicalPath string             `json:"logical_path"`
	CourseID    int64              `json:"course_id"`
}

func (q *Queries) FileObject(ctx context.Context, id string) (FileObjectRow, error) {
	row := q.db.QueryRow(ctx, fileObject, id)
	var i FileObjectRow
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.Key,
		&i.VersionID,
		&i.Sha256,
		&i.Bytes,
		&i.MediaType,
		&i.CreatedAt,
		&i.LogicalPath,
		&i.CourseID,
	)
	return i, err
}

const registerObject = `-- name: RegisterObject :execrows
INSERT INTO app.objects(id,bucket,key,version_id,sha256,bytes,media_type) VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(id) DO UPDATE SET id=excluded.id
WHERE app.objects.bucket=excluded.bucket AND app.objects.key=excluded.key
AND app.objects.version_id=excluded.version_id AND app.objects.sha256=excluded.sha256
AND app.objects.bytes=excluded.bytes
`

type RegisterObjectParams struct {
	ID        string `json:"id"`
	Bucket    string `json:"bucket"`
	Key       string `json:"key"`
	VersionID string `json:"version_id"`
	Sha256    string `json:"sha256"`
	Bytes     int64  `json:"bytes"`
	MediaType string `json:"media_type"`
}

func (q *Queries) RegisterObject(ctx context.Context, arg RegisterObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, registerObject,
		arg.ID,
		arg.Bucket,
		arg.Key,
		arg.VersionID,
		arg.Sha256,
		arg.Bytes,
		arg.MediaType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerRevision = `-- name: RegisterRevision :exec
INSERT INTO app.document_revisions(id,document_id,course_id,logical_path,object_id) VALUES($1,$2,$3,$4,$5)
ON CONFLICT(document_id,object_id) DO NOTHING
`

type RegisterRevisionParams struct {
	ID          string `json:"id"`
	DocumentID  string `json:"document_id"`
	CourseID    int64  `json:"course_id"`
	LogicalPath string `json:"logical_path"`
	ObjectID    string `json:"object_id"`
}

func (q *Queries) RegisterRevision(ctx context.Context, arg RegisterRevisionParams) error {
	_, err := q.db.Exec(ctx, registerRevision,
		arg.ID,
		arg.DocumentID,
		arg.CourseID,
		arg.LogicalPath,
		arg.ObjectID,
	)
	return err
}
