// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package queries

import (
	"context"
)

const claimCommands = `-- name: ClaimCommands :many
UPDATE app.control_commands SET status='running',attempts=attempts+1,claimed_at=now()
WHERE id IN (SELECT pending.id FROM app.control_commands pending WHERE pending.queue=$1 AND pending.status='pending' AND pending.available_at<=now()
ORDER BY pending.available_at,pending.id FOR UPDATE SKIP LOCKED LIMIT $2) RETURNING id, queue, action, payload, status, attempts, available_at, claimed_at, error
`

type ClaimCommandsParams struct {
	Queue string `json:"queue"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ClaimCommands(ctx context.Context, arg ClaimCommandsParams) ([]AppControlCommand, error) {
	rows, err := q.db.Query(ctx, claimCommands, arg.Queue, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppControlCommand{}
	for rows.Next() {
		var i AppControlCommand
		if err := rows.Scan(
			&i.ID,
			&i.Queue,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.ClaimedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeCommand = `-- name: CompleteCommand :exec
DELETE FROM app.control_commands WHERE id=$1
`

func (q *Queries) CompleteCommand(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, completeCommand, id)
	return err
}

const enqueueCommand = `-- name: EnqueueCommand :exec
INSERT INTO app.control_commands(id,queue,action,payload) VALUES($1,$2,$3,$4)
`

type EnqueueCommandParams struct {
	ID      string `json:"id"`
	Queue   string `json:"queue"`
	Action  string `json:"action"`
	Payload []byte `json:"payload"`
}

func (q *Queries) EnqueueCommand(ctx context.Context, arg EnqueueCommandParams) error {
	_, err := q.db.Exec(ctx, enqueueCommand,
		arg.ID,
		arg.Queue,
		arg.Action,
		arg.Payload,
	)
	return err
}

const failCommand = `-- name: FailCommand :exec
UPDATE app.control_commands SET status=$2,error=$3,available_at=now()+$4::bigint*interval '1 second',claimed_at=NULL WHERE id=$1
`

type FailCommandParams struct {
	ID           string  `json:"id"`
	Status       string  `json:"status"`
	Error        *string `json:"error"`
	DelaySeconds int64   `json:"delay_seconds"`
}

func (q *Queries) FailCommand(ctx context.Context, arg FailCommandParams) error {
	_, err := q.db.Exec(ctx, failCommand,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.DelaySeconds,
	)
	return err
}

const pendingCommand = `-- name: PendingCommand :one
SELECT id FROM app.control_commands WHERE queue=$1 AND action=$2 AND status='pending'
ORDER BY available_at,id LIMIT 1 FOR UPDATE
`

type PendingCommandParams struct {
	Queue  string `json:"queue"`
	Action string `json:"action"`
}

func (q *Queries) PendingCommand(ctx context.Context, arg PendingCommandParams) (string, error) {
	row := q.db.QueryRow(ctx, pendingCommand, arg.Queue, arg.Action)
	var id string
	err := row.Scan(&id)
	return id, err
}

const queueLock = `-- name: QueueLock :exec
SELECT pg_advisory_xact_lock(hashtext($1)::bigint)
`

func (q *Queries) QueueLock(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, queueLock, hashtext)
	return err
}

const recoverCommands = `-- name: RecoverCommands :exec
UPDATE app.control_commands SET status='pending',claimed_at=NULL WHERE status='running'
`

func (q *Queries) RecoverCommands(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverCommands)
	return err
}
