// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tree.sql

package queries

import (
	"context"
)

const treeFiles = `-- name: TreeFiles :many
SELECT f.node_id,f.url,f.name,f.md5_hash,f.etag,f.last_updated,f.local_path,f.redirect_url
FROM app.files f JOIN app.nodes n ON n.id=f.node_id WHERE n.course_id=$1 ORDER BY f.id
`

type TreeFilesRow struct {
	NodeID      int64   `json:"node_id"`
	Url         string  `json:"url"`
	Name        string  `json:"name"`
	Md5Hash     *string `json:"md5_hash"`
	Etag        *string `json:"etag"`
	LastUpdated *string `json:"last_updated"`
	LocalPath   *string `json:"local_path"`
	RedirectUrl *string `json:"redirect_url"`
}

func (q *Queries) TreeFiles(ctx context.Context, courseID int64) ([]TreeFilesRow, error) {
	rows, err := q.db.Query(ctx, treeFiles, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreeFilesRow{}
	for rows.Next() {
		var i TreeFilesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.Url,
			&i.Name,
			&i.Md5Hash,
			&i.Etag,
			&i.LastUpdated,
			&i.LocalPath,
			&i.RedirectUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const treeNodes = `-- name: TreeNodes :many
SELECT id,parent_id,name,url,local_path FROM app.nodes WHERE course_id=$1 ORDER BY id
`

type TreeNodesRow struct {
	ID        int64  `json:"id"`
	ParentID  *int64 `json:"parent_id"`
	Name      string `json:"name"`
	Url       string `json:"url"`
	LocalPath string `json:"local_path"`
}

func (q *Queries) TreeNodes(ctx context.Context, courseID int64) ([]TreeNodesRow, error) {
	rows, err := q.db.Query(ctx, treeNodes, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreeNodesRow{}
	for rows.Next() {
		var i TreeNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Url,
			&i.LocalPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
