CREATE SCHEMA IF NOT EXISTS app;
SET search_path TO app, public;

CREATE TABLE app.schema_version (
                id BIGINT PRIMARY KEY CHECK (id = 1),
                version BIGINT NOT NULL,
                updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
            );

CREATE TABLE app.credentials (
                id BIGINT PRIMARY KEY,
                username TEXT NOT NULL,
                password TEXT NOT NULL
            );

CREATE TABLE app.app_data (
                key TEXT PRIMARY KEY,
                value BYTEA
            );

CREATE TABLE app.courses (
                id BIGINT PRIMARY KEY,
                name TEXT NOT NULL,
                webdav_folder TEXT NOT NULL,
                sort_order BIGINT DEFAULT 0,
                hidden BIGINT NOT NULL DEFAULT 0,
                short_name TEXT
            );

CREATE TABLE app.nodes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                parent_id BIGINT,
                name TEXT NOT NULL,
                url TEXT NOT NULL,
                local_path TEXT NOT NULL,  -- WebDAV path (kept as local_path for backward compatibility)
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE,
                FOREIGN KEY (parent_id) REFERENCES app.nodes (id) ON DELETE CASCADE
            );

CREATE TABLE app.files (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                node_id BIGINT NOT NULL,
                url TEXT NOT NULL,
                name TEXT NOT NULL,
                md5_hash TEXT,
                etag TEXT,
                redirect_url TEXT, last_updated TEXT, local_path TEXT,
                FOREIGN KEY (node_id) REFERENCES app.nodes (id) ON DELETE CASCADE
            );

CREATE TABLE app.change_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                change_type TEXT NOT NULL,
                file_path TEXT NOT NULL,
                timestamp TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.change_records (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                change_no TEXT NOT NULL,
                timestamp TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                message TEXT,
                changes_count BIGINT DEFAULT 0,
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE,
                UNIQUE(course_id, change_no)
            );

CREATE TABLE app.change_record_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                change_record_id BIGINT NOT NULL,
                change_type TEXT NOT NULL,
                file_path TEXT NOT NULL,
                display_name TEXT,
                redirect_url TEXT,
                diff_webdav_path TEXT,
                FOREIGN KEY (change_record_id) REFERENCES app.change_records (id) ON DELETE CASCADE
            );

CREATE TABLE app.webhook_config (
                id BIGINT PRIMARY KEY,
                webhook_url TEXT NOT NULL
            );

CREATE TABLE app.webdav_config (
                id BIGINT PRIMARY KEY,
                hostname TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                disable_check BIGINT DEFAULT 0,
                timeout BIGINT DEFAULT 30
            );

CREATE TABLE app.preferences (
                id BIGINT PRIMARY KEY,
                check_interval_minutes BIGINT DEFAULT 60,
                max_concurrent_downloads BIGINT DEFAULT 3,
                request_timeout_seconds BIGINT DEFAULT 30,
                retry_attempts BIGINT DEFAULT 3,
                notification_enabled BIGINT DEFAULT 1,
                notification_on_error BIGINT DEFAULT 1,
                download_base_path TEXT NOT NULL DEFAULT '/University'
            , global_feed_dept_enabled BIGINT DEFAULT 1, global_feed_undergrad_enabled BIGINT DEFAULT 0, global_feed_rector_enabled BIGINT DEFAULT 0, semester_start TEXT DEFAULT NULL, semester_end TEXT DEFAULT NULL);

CREATE TABLE app.check_status (
                id BIGINT PRIMARY KEY,
                is_checking BIGINT DEFAULT 0,
                started_at TEXT,
                current_course_id BIGINT,
                last_check_at TEXT,
                last_check_result TEXT,
                last_error TEXT,
                last_files_added BIGINT,
                last_files_changed BIGINT,
                FOREIGN KEY (current_course_id) REFERENCES app.courses (id) ON DELETE SET NULL
            );

CREATE TABLE app.announcements (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                announcement_id TEXT NOT NULL,
                title TEXT NOT NULL,
                link TEXT NOT NULL,
                description TEXT,
                pub_date TEXT,
                fetched_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE,
                UNIQUE(course_id, announcement_id)
            );

CREATE TABLE app.file_versions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                file_path TEXT NOT NULL,
                version_webdav_path TEXT,
                change_type TEXT NOT NULL,
                timestamp TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                display_name TEXT,
                redirect_url TEXT,
                diff_webdav_path TEXT,
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.file_study (
                course_id BIGINT NOT NULL,
                file_path TEXT NOT NULL,
                level BIGINT NOT NULL DEFAULT 0,
                last_updated TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                PRIMARY KEY (course_id, file_path),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.collapsed_course_folders (
                course_id BIGINT NOT NULL,
                folder_key TEXT NOT NULL,
                collapsed BIGINT NOT NULL DEFAULT 1 CHECK(collapsed IN (0, 1)),
                updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                PRIMARY KEY (course_id, folder_key),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.discord_course_channels (
                root_channel_id TEXT PRIMARY KEY,
                course_id BIGINT NOT NULL,
                updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.discord_export_settings (
                id BIGINT PRIMARY KEY CHECK (id = 1),
                enabled BIGINT NOT NULL DEFAULT 0,
                token TEXT NOT NULL DEFAULT '',
                interval_seconds BIGINT NOT NULL DEFAULT 3600,
                include_threads TEXT NOT NULL DEFAULT 'All',
                media BIGINT NOT NULL DEFAULT 1,
                parallel BIGINT NOT NULL DEFAULT 1,
                updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
            );

CREATE TABLE app.study_sessions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                timestamp TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                note TEXT,
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.study_planner_settings (
                id BIGINT PRIMARY KEY CHECK (id = 1),
                daily_blocks BIGINT NOT NULL DEFAULT 6,
                block_minutes BIGINT NOT NULL DEFAULT 50,
                weekly_minutes_json TEXT NOT NULL DEFAULT
                    '{"0":150,"1":150,"2":150,"3":150,"4":150,"5":400,"6":400}',
                blackout_dates_json TEXT NOT NULL DEFAULT '[]',
                max_courses_per_day BIGINT NOT NULL DEFAULT 2
            );

CREATE TABLE app.course_exam_plans (
                course_id BIGINT PRIMARY KEY,
                exam_at TEXT,
                remaining_blocks BIGINT NOT NULL DEFAULT 0,
                importance DOUBLE PRECISION NOT NULL DEFAULT 1.0,
                max_daily_blocks BIGINT NOT NULL DEFAULT 3,
                enabled BIGINT NOT NULL DEFAULT 0,
                commitment TEXT NOT NULL DEFAULT 'committed',
                target_grade DOUBLE PRECISION NOT NULL DEFAULT 5.0,
                planning_notes TEXT,
                updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.study_unit_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                plan_revision TEXT NOT NULL,
                action_id TEXT NOT NULL,
                unit_key TEXT NOT NULL,
                event_type TEXT NOT NULL CHECK(event_type IN (
                    'started', 'completed', 'partial', 'stuck', 'deferred',
                    'recall_answered', 'exam_question_attempted'
                )),
                idempotency_key TEXT,
                confidence BIGINT CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 5),
                actual_minutes BIGINT CHECK(actual_minutes IS NULL OR actual_minutes >= 0),
                score DOUBLE PRECISION,
                note TEXT,
                created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.practice_attempts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                unit_key TEXT NOT NULL,
                question_id TEXT NOT NULL,
                question_key TEXT NOT NULL DEFAULT '',
                set_hash TEXT NOT NULL DEFAULT '',
                blueprint_revision_hash TEXT NOT NULL DEFAULT '',
                outcome TEXT NOT NULL CHECK(outcome IN (
                    'correct', 'partial', 'incorrect', 'skipped'
                )),
                grading_mode TEXT NOT NULL DEFAULT 'self'
                    CHECK(grading_mode IN ('self', 'ai')),
                confidence BIGINT
                    CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 5),
                seconds BIGINT CHECK(seconds IS NULL OR seconds >= 0),
                answer TEXT,
                note TEXT,
                idempotency_key TEXT,
                study_event_id BIGINT,
                attempted_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.chat_conversations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                created_at TEXT NOT NULL
                    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS.MS')),
                updated_at TEXT NOT NULL
                    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS.MS'))
            );

CREATE TABLE app.chat_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                conversation_id BIGINT NOT NULL,
                role TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
                content TEXT NOT NULL,
                consulted_json TEXT,
                model TEXT,
                created_at TEXT NOT NULL
                    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS.MS')),
                FOREIGN KEY (conversation_id)
                    REFERENCES app.chat_conversations (id) ON DELETE CASCADE
            );

CREATE TABLE app.study_workspace_sessions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                action_id TEXT NOT NULL DEFAULT '',
                unit_key TEXT NOT NULL DEFAULT '',
                plan_revision TEXT NOT NULL DEFAULT '',
                client_session_key TEXT NOT NULL,
                planned_minutes BIGINT
                    CHECK(planned_minutes IS NULL OR planned_minutes >= 0),
                active_seconds BIGINT NOT NULL DEFAULT 0
                    CHECK(active_seconds >= 0),
                visible_seconds BIGINT NOT NULL DEFAULT 0
                    CHECK(visible_seconds >= 0),
                outcome TEXT CHECK(outcome IS NULL OR outcome IN (
                    'completed', 'partial', 'stuck', 'deferred', 'abandoned'
                )),
                note TEXT,
                started_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                last_seen_at TEXT,
                ended_at TEXT,
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.study_reading_spans (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id BIGINT NOT NULL,
                course_id BIGINT NOT NULL,
                document_id TEXT NOT NULL,
                source_hash TEXT NOT NULL DEFAULT '',
                page_number BIGINT NOT NULL CHECK(page_number > 0),
                action_id TEXT NOT NULL DEFAULT '',
                unit_key TEXT NOT NULL DEFAULT '',
                plan_revision TEXT NOT NULL DEFAULT '',
                active_seconds BIGINT NOT NULL DEFAULT 0
                    CHECK(active_seconds >= 0),
                visible_seconds BIGINT NOT NULL DEFAULT 0
                    CHECK(visible_seconds >= 0),
                started_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                ended_at TEXT,
                FOREIGN KEY (session_id)
                    REFERENCES app.study_workspace_sessions (id) ON DELETE CASCADE,
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE,
                UNIQUE(session_id, document_id, page_number)
            );

CREATE TABLE app.study_reading_beats (
                session_id BIGINT NOT NULL,
                sequence BIGINT NOT NULL CHECK(sequence >= 0),
                recorded_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                PRIMARY KEY (session_id, sequence),
                FOREIGN KEY (session_id)
                    REFERENCES app.study_workspace_sessions (id) ON DELETE CASCADE
            );

CREATE TABLE app.study_annotations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                document_id TEXT NOT NULL,
                source_hash TEXT NOT NULL DEFAULT '',
                page_number BIGINT NOT NULL CHECK(page_number > 0),
                kind TEXT NOT NULL DEFAULT 'highlight' CHECK(kind IN (
                    'highlight', 'note', 'question', 'bookmark'
                )),
                origin TEXT NOT NULL DEFAULT 'learner'
                    CHECK(origin IN ('learner', 'ai')),
                status TEXT NOT NULL DEFAULT 'active'
                    CHECK(status IN ('active', 'orphaned', 'deleted')),
                color TEXT NOT NULL DEFAULT 'yellow',
                quote TEXT NOT NULL DEFAULT '',
                prefix TEXT NOT NULL DEFAULT '',
                suffix TEXT NOT NULL DEFAULT '',
                char_start BIGINT,
                char_end BIGINT,
                rects_json TEXT NOT NULL DEFAULT '[]',
                chunk_id TEXT,
                body TEXT,
                tags_json TEXT NOT NULL DEFAULT '[]',
                action_id TEXT NOT NULL DEFAULT '',
                unit_key TEXT NOT NULL DEFAULT '',
                plan_revision TEXT NOT NULL DEFAULT '',
                session_id BIGINT,
                idempotency_key TEXT,
                created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.external_material_metadata (
                course_id BIGINT NOT NULL,
                source_path TEXT NOT NULL,
                material_type TEXT NOT NULL CHECK(material_type IN (
                    'past_paper', 'student_notes', 'study_guide', 'textbook',
                    'exercise_solution', 'lecture_material', 'other'
                )),
                source_label TEXT,
                notes TEXT,
                created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                PRIMARY KEY (course_id, source_path),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.global_announcements (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                feed_key TEXT NOT NULL,
                announcement_id TEXT NOT NULL,
                title TEXT NOT NULL,
                link TEXT NOT NULL,
                description TEXT,
                pub_date TEXT,
                fetched_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                UNIQUE(feed_key, announcement_id)
            );

CREATE TABLE app.exercises (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                exercise_id TEXT NOT NULL,
                title TEXT NOT NULL,
                link TEXT NOT NULL,
                deadline TEXT,
                submission_status TEXT,
                grade TEXT,
                work_type TEXT,
                description TEXT,
                start_date TEXT,
                max_grade TEXT,
                assignment_file_name TEXT,
                assignment_file_url TEXT,
                grade_comments TEXT,
                submission_date TEXT,
                ignored BIGINT NOT NULL DEFAULT 0,
                fetched_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                UNIQUE(course_id, exercise_id),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.study_plan_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id BIGINT NOT NULL,
                scheduled_date TEXT NOT NULL,
                kind TEXT NOT NULL CHECK(kind IN ('study', 'review')),
                completed BIGINT NOT NULL DEFAULT 0,
                created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.study_review_overrides (
                course_id BIGINT NOT NULL,
                review_offset BIGINT NOT NULL,
                scheduled_date TEXT NOT NULL,
                PRIMARY KEY (course_id, review_offset),
                FOREIGN KEY (course_id) REFERENCES app.courses (id) ON DELETE CASCADE
            );

CREATE TABLE app.sync_status (
                job TEXT PRIMARY KEY,
                last_run_at TEXT,
                last_result TEXT,
                last_error TEXT,
                last_message TEXT
            );

CREATE INDEX idx_study_unit_events_action
            ON app.study_unit_events(plan_revision, action_id, created_at)
        ;

CREATE INDEX idx_practice_attempts_question
            ON app.practice_attempts(question_id, attempted_at)
        ;

CREATE INDEX idx_practice_attempts_course
            ON app.practice_attempts(course_id, unit_key, attempted_at)
        ;

CREATE UNIQUE INDEX idx_practice_attempts_idempotency
            ON app.practice_attempts(idempotency_key)
            WHERE idempotency_key IS NOT NULL
        ;

CREATE INDEX idx_chat_messages_conversation
            ON app.chat_messages(conversation_id, id)
        ;

CREATE INDEX idx_chat_conversations_updated
            ON app.chat_conversations(updated_at DESC, id DESC)
        ;

CREATE UNIQUE INDEX idx_workspace_sessions_key
            ON app.study_workspace_sessions(client_session_key)
        ;

CREATE INDEX idx_workspace_sessions_action
            ON app.study_workspace_sessions(course_id, action_id, started_at)
        ;

CREATE INDEX idx_reading_spans_document
            ON app.study_reading_spans(document_id, page_number)
        ;

CREATE INDEX idx_reading_spans_course_document
            ON app.study_reading_spans(course_id, document_id, page_number)
        ;

CREATE INDEX idx_reading_spans_action
            ON app.study_reading_spans(course_id, action_id)
        ;

CREATE INDEX idx_annotations_document
            ON app.study_annotations(document_id, page_number, status)
        ;

CREATE INDEX idx_annotations_course
            ON app.study_annotations(course_id, updated_at DESC)
        ;

CREATE UNIQUE INDEX idx_annotations_idempotency
            ON app.study_annotations(idempotency_key)
            WHERE idempotency_key IS NOT NULL
        ;

CREATE INDEX idx_external_material_metadata_course
            ON app.external_material_metadata(course_id, material_type, updated_at)
        ;

CREATE UNIQUE INDEX idx_study_unit_events_idempotency
            ON app.study_unit_events(idempotency_key)
            WHERE idempotency_key IS NOT NULL
        ;

INSERT INTO app.schema_version VALUES ('1','38','2026-09-07 18:34:08');

INSERT INTO app.study_planner_settings VALUES ('1','6','50','{"0":150,"1":150,"2":150,"3":150,"4":150,"5":400,"6":400}','[]','2');
