CREATE SCHEMA IF NOT EXISTS knowledge;
SET search_path TO knowledge, public;

CREATE TABLE knowledge.knowledge_schema_version (
    id BIGINT PRIMARY KEY CHECK (id = 1), version BIGINT NOT NULL, updated_at TEXT NOT NULL
);

CREATE TABLE knowledge.documents (
    id TEXT PRIMARY KEY,
    course_id BIGINT NOT NULL,
    course_name TEXT NOT NULL,
    course_short_name TEXT,
    source_path TEXT NOT NULL,
    source_origin TEXT NOT NULL DEFAULT 'eclass',
    normalized_path TEXT NOT NULL,
    source_url TEXT,
    display_name TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    source_fingerprint TEXT NOT NULL DEFAULT '',
    source_etag TEXT,
    content_hash_verified BIGINT NOT NULL DEFAULT 0,
    mime_type TEXT,
    response_mime_type TEXT,
    document_kind TEXT NOT NULL,
    academic_year TEXT,
    source_modified_at TEXT,
    is_current BIGINT NOT NULL DEFAULT 1,
    status TEXT NOT NULL,
    page_count BIGINT,
    source_size_bytes BIGINT,
    character_count BIGINT,
    word_count BIGINT,
    reading_minutes BIGINT,
    complexity_score BIGINT,
    complexity_label TEXT,
    language_hint TEXT,
    extractor_name TEXT,
    extractor_version TEXT,
    indexed_at TEXT,
    error TEXT,
    diagnostic_reason TEXT,
    warnings_json TEXT NOT NULL DEFAULT '[]',
    UNIQUE(course_id, normalized_path)
);

CREATE TABLE knowledge.archive_members (
    child_document_id TEXT PRIMARY KEY,
    parent_document_id TEXT NOT NULL,
    member_path TEXT NOT NULL,
    normalized_member_path TEXT NOT NULL,
    member_chain_json TEXT NOT NULL,
    depth BIGINT NOT NULL CHECK(depth >= 0),
    archive_format TEXT NOT NULL DEFAULT 'zip',
    parent_source_hash TEXT NOT NULL,
    parent_source_fingerprint TEXT NOT NULL,
    member_hash TEXT NOT NULL,
    crc32 BIGINT NOT NULL,
    compressed_size BIGINT NOT NULL,
    expanded_size BIGINT NOT NULL,
    member_kind TEXT NOT NULL,
    mime_type TEXT,
    FOREIGN KEY(child_document_id) REFERENCES knowledge.documents(id) ON DELETE CASCADE,
    FOREIGN KEY(parent_document_id) REFERENCES knowledge.documents(id) ON DELETE CASCADE,
    UNIQUE(parent_document_id, normalized_member_path)
);

CREATE TABLE knowledge.chunks (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL,
    ordinal BIGINT NOT NULL,
    locator_type TEXT NOT NULL,
    locator_start TEXT,
    locator_end TEXT,
    heading TEXT,
    text TEXT NOT NULL,
    normalized_text TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY(document_id) REFERENCES knowledge.documents(id) ON DELETE CASCADE,
    UNIQUE(document_id, ordinal)
);

CREATE TABLE knowledge.index_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    source_path TEXT NOT NULL,
    normalized_path TEXT NOT NULL,
    requested_hash TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL CHECK(action IN ('upsert', 'delete')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'running', 'completed', 'failed', 'stale')),
    attempts BIGINT NOT NULL DEFAULT 0,
    available_at TEXT NOT NULL,
    claimed_at TEXT,
    completed_at TEXT,
    error TEXT,
    error_category TEXT,
    last_error TEXT,
    UNIQUE(course_id, normalized_path, requested_hash, action)
);

CREATE TABLE knowledge.knowledge_state (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);

CREATE TABLE knowledge.chunk_embeddings (
    chunk_id TEXT NOT NULL,
    model TEXT NOT NULL,
    vector BYTEA NOT NULL,
    dimensions BIGINT NOT NULL,
    PRIMARY KEY(chunk_id, model),
    FOREIGN KEY(chunk_id) REFERENCES knowledge.chunks(id) ON DELETE CASCADE
);

CREATE TABLE knowledge.document_enrichments (
    document_id TEXT PRIMARY KEY,
    source_hash TEXT NOT NULL,
    context_hash TEXT NOT NULL DEFAULT '',
    analysis_version TEXT NOT NULL DEFAULT '1',
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending', 'running', 'ready', 'failed')),
    model TEXT NOT NULL,
    payload_json TEXT,
    priority BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    available_at TEXT NOT NULL,
    claimed_at TEXT,
    generated_at TEXT,
    error TEXT,
    FOREIGN KEY(document_id) REFERENCES knowledge.documents(id) ON DELETE CASCADE
);

CREATE TABLE knowledge.page_enrichments (
    document_id TEXT NOT NULL,
    page_number BIGINT NOT NULL CHECK(page_number > 0),
    source_hash TEXT NOT NULL,
    analysis_version TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending', 'running', 'ready', 'failed')),
    model TEXT NOT NULL,
    requested_model TEXT NOT NULL,
    payload_json TEXT,
    priority BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    available_at TEXT NOT NULL,
    claimed_at TEXT,
    generated_at TEXT,
    error TEXT,
    PRIMARY KEY(document_id, page_number),
    FOREIGN KEY(document_id) REFERENCES knowledge.documents(id) ON DELETE CASCADE
);

CREATE TABLE knowledge.course_blueprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    revision BIGINT NOT NULL CHECK(revision > 0),
    revision_hash TEXT NOT NULL UNIQUE,
    evidence_hash TEXT NOT NULL,
    evidence_packet_json TEXT NOT NULL,
    analysis_version TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending', 'running', 'ready', 'failed', 'stale')),
    requested_model TEXT NOT NULL,
    model TEXT NOT NULL,
    payload_json TEXT,
    priority BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    available_at TEXT NOT NULL,
    claimed_at TEXT,
    created_at TEXT NOT NULL,
    generated_at TEXT,
    finished_at TEXT,
    error TEXT,
    superseded_by_revision BIGINT,
    UNIQUE(course_id, revision)
);

CREATE TABLE knowledge.practice_question_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    unit_key TEXT NOT NULL,
    set_hash TEXT NOT NULL UNIQUE,
    blueprint_revision_hash TEXT NOT NULL,
    evidence_hash TEXT NOT NULL,
    evidence_packet_json TEXT NOT NULL,
    analysis_version TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending', 'running', 'ready', 'failed', 'stale')),
    requested_model TEXT NOT NULL,
    model TEXT NOT NULL,
    payload_json TEXT,
    priority BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    available_at TEXT NOT NULL,
    claimed_at TEXT,
    created_at TEXT NOT NULL,
    generated_at TEXT,
    finished_at TEXT,
    error TEXT
);

CREATE TABLE knowledge.practice_questions (
    question_id TEXT NOT NULL,
    set_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    unit_key TEXT NOT NULL,
    ordinal BIGINT NOT NULL,
    question_key TEXT NOT NULL,
    response_mode TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    estimated_minutes BIGINT NOT NULL,
    payload_json TEXT NOT NULL,
    PRIMARY KEY(set_id, question_id),
    FOREIGN KEY(set_id) REFERENCES knowledge.practice_question_sets(id) ON DELETE CASCADE
);

CREATE INDEX idx_documents_course_current ON knowledge.documents(course_id, is_current, status);

CREATE INDEX idx_archive_members_parent
    ON knowledge.archive_members(parent_document_id, normalized_member_path);

CREATE INDEX idx_chunks_document_locator ON knowledge.chunks(document_id, locator_type, locator_start);

CREATE INDEX idx_jobs_claim ON knowledge.index_jobs(status, available_at, id);

CREATE INDEX idx_document_enrichments_claim
    ON knowledge.document_enrichments(status, available_at, document_id);

CREATE INDEX idx_document_enrichments_priority_claim
    ON knowledge.document_enrichments(status, priority DESC, available_at, document_id);

CREATE INDEX idx_page_enrichments_claim
    ON knowledge.page_enrichments(status, priority DESC, available_at, document_id, page_number);

CREATE INDEX idx_course_blueprints_claim
    ON knowledge.course_blueprints(status, priority DESC, available_at, id);

CREATE INDEX idx_course_blueprints_history
    ON knowledge.course_blueprints(course_id, revision DESC);

CREATE UNIQUE INDEX idx_course_blueprints_ready
    ON knowledge.course_blueprints(course_id) WHERE status='ready';

CREATE UNIQUE INDEX idx_course_blueprints_active_revision
    ON knowledge.course_blueprints(course_id, revision_hash)
    WHERE status IN ('pending', 'running', 'ready');

CREATE INDEX idx_practice_sets_claim
    ON knowledge.practice_question_sets(status, priority DESC, available_at, id);

CREATE INDEX idx_practice_sets_revision
    ON knowledge.practice_question_sets(course_id, blueprint_revision_hash, status);

CREATE UNIQUE INDEX idx_practice_sets_ready
    ON knowledge.practice_question_sets(course_id, unit_key) WHERE status='ready';

CREATE UNIQUE INDEX idx_practice_sets_active
    ON knowledge.practice_question_sets(course_id, unit_key)
    WHERE status IN ('pending', 'running');

CREATE INDEX idx_practice_questions_unit
    ON knowledge.practice_questions(course_id, unit_key, ordinal);

CREATE INDEX idx_practice_questions_identity
    ON knowledge.practice_questions(question_id);

INSERT INTO knowledge.knowledge_schema_version VALUES ('1','17','2026-09-07T18:34:09.079831+00:00');
