// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package queries

import (
	"context"
)

const indexEmbedding = `-- name: IndexEmbedding :exec
INSERT INTO knowledge.chunk_embeddings(chunk_id,model,vector,dimensions) VALUES($1,$2,$3,$4)
ON CONFLICT(chunk_id,model) DO UPDATE SET vector=excluded.vector,dimensions=excluded.dimensions
`

type IndexEmbeddingParams struct {
	ChunkID    string `json:"chunk_id"`
	Model      string `json:"model"`
	Vector     []byte `json:"vector"`
	Dimensions int64  `json:"dimensions"`
}

func (q *Queries) IndexEmbedding(ctx context.Context, arg IndexEmbeddingParams) error {
	_, err := q.db.Exec(ctx, indexEmbedding,
		arg.ChunkID,
		arg.Model,
		arg.Vector,
		arg.Dimensions,
	)
	return err
}
