// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAnnouncement struct {
	ID             int64   `json:"id"`
	CourseID       int64   `json:"course_id"`
	AnnouncementID string  `json:"announcement_id"`
	Title          string  `json:"title"`
	Link           string  `json:"link"`
	Description    *string `json:"description"`
	PubDate        *string `json:"pub_date"`
	FetchedAt      *string `json:"fetched_at"`
}

type AppAppDatum struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

type AppChangeHistory struct {
	ID         int64   `json:"id"`
	CourseID   int64   `json:"course_id"`
	ChangeType string  `json:"change_type"`
	FilePath   string  `json:"file_path"`
	Timestamp  *string `json:"timestamp"`
}

type AppChangeRecord struct {
	ID           int64   `json:"id"`
	CourseID     int64   `json:"course_id"`
	ChangeNo     string  `json:"change_no"`
	Timestamp    *string `json:"timestamp"`
	Message      *string `json:"message"`
	ChangesCount *int64  `json:"changes_count"`
}

type AppChangeRecordItem struct {
	ID              int64   `json:"id"`
	ChangeRecordID  int64   `json:"change_record_id"`
	ChangeType      string  `json:"change_type"`
	FilePath        string  `json:"file_path"`
	DisplayName     *string `json:"display_name"`
	RedirectUrl     *string `json:"redirect_url"`
	DiffWebdavPath  *string `json:"diff_webdav_path"`
	PdfDifferenceID *string `json:"pdf_difference_id"`
}

type AppChatConversation struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AppChatMessage struct {
	ID             int64   `json:"id"`
	ConversationID int64   `json:"conversation_id"`
	Role           string  `json:"role"`
	Content        string  `json:"content"`
	ConsultedJson  *string `json:"consulted_json"`
	Model          *string `json:"model"`
	CreatedAt      string  `json:"created_at"`
}

type AppCheckStatus struct {
	ID               int64   `json:"id"`
	IsChecking       *int64  `json:"is_checking"`
	StartedAt        *string `json:"started_at"`
	CurrentCourseID  *int64  `json:"current_course_id"`
	LastCheckAt      *string `json:"last_check_at"`
	LastCheckResult  *string `json:"last_check_result"`
	LastError        *string `json:"last_error"`
	LastFilesAdded   *int64  `json:"last_files_added"`
	LastFilesChanged *int64  `json:"last_files_changed"`
}

type AppCollapsedCourseFolder struct {
	CourseID  int64   `json:"course_id"`
	FolderKey string  `json:"folder_key"`
	Collapsed int64   `json:"collapsed"`
	UpdatedAt *string `json:"updated_at"`
}

type AppControlCommand struct {
	ID          string             `json:"id"`
	Queue       string             `json:"queue"`
	Action      string             `json:"action"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	Error       *string            `json:"error"`
}

type AppCourse struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	WebdavFolder string  `json:"webdav_folder"`
	SortOrder    *int64  `json:"sort_order"`
	Hidden       int64   `json:"hidden"`
	ShortName    *string `json:"short_name"`
}

type AppCourseExamPlan struct {
	CourseID        int64   `json:"course_id"`
	ExamAt          *string `json:"exam_at"`
	RemainingBlocks int64   `json:"remaining_blocks"`
	Importance      float64 `json:"importance"`
	MaxDailyBlocks  int64   `json:"max_daily_blocks"`
	Enabled         int64   `json:"enabled"`
	Commitment      string  `json:"commitment"`
	TargetGrade     float64 `json:"target_grade"`
	PlanningNotes   *string `json:"planning_notes"`
	UpdatedAt       *string `json:"updated_at"`
}

type AppCourseMutation struct {
	Action         string             `json:"action"`
	CourseID       int64              `json:"course_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AppCredential struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type AppDiscordCourseChannel struct {
	RootChannelID string  `json:"root_channel_id"`
	CourseID      int64   `json:"course_id"`
	UpdatedAt     *string `json:"updated_at"`
}

type AppDiscordDiscoveredChannel struct {
	ChannelID int64              `json:"channel_id"`
	RootID    int64              `json:"root_id"`
	GuildID   int64              `json:"guild_id"`
	Name      string             `json:"name"`
	IsThread  bool               `json:"is_thread"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AppDiscordExportSetting struct {
	ID              int64   `json:"id"`
	Enabled         int64   `json:"enabled"`
	Token           string  `json:"token"`
	IntervalSeconds int64   `json:"interval_seconds"`
	IncludeThreads  string  `json:"include_threads"`
	Media           int64   `json:"media"`
	Parallel        int64   `json:"parallel"`
	UpdatedAt       *string `json:"updated_at"`
}

type AppDiscordRootChannel struct {
	RootChannelID string             `json:"root_channel_id"`
	Name          string             `json:"name"`
	Metadata      []byte             `json:"metadata"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppDocumentRevision struct {
	ID          string             `json:"id"`
	DocumentID  string             `json:"document_id"`
	CourseID    int64              `json:"course_id"`
	LogicalPath string             `json:"logical_path"`
	ObjectID    string             `json:"object_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type AppExercise struct {
	ID                 int64   `json:"id"`
	CourseID           int64   `json:"course_id"`
	ExerciseID         string  `json:"exercise_id"`
	Title              string  `json:"title"`
	Link               string  `json:"link"`
	Deadline           *string `json:"deadline"`
	SubmissionStatus   *string `json:"submission_status"`
	Grade              *string `json:"grade"`
	WorkType           *string `json:"work_type"`
	Description        *string `json:"description"`
	StartDate          *string `json:"start_date"`
	MaxGrade           *string `json:"max_grade"`
	AssignmentFileName *string `json:"assignment_file_name"`
	AssignmentFileUrl  *string `json:"assignment_file_url"`
	GradeComments      *string `json:"grade_comments"`
	SubmissionDate     *string `json:"submission_date"`
	Ignored            int64   `json:"ignored"`
	FetchedAt          *string `json:"fetched_at"`
}

type AppExternalMaterialMetadatum struct {
	CourseID     int64   `json:"course_id"`
	SourcePath   string  `json:"source_path"`
	MaterialType string  `json:"material_type"`
	SourceLabel  *string `json:"source_label"`
	Notes        *string `json:"notes"`
	CreatedAt    *string `json:"created_at"`
	UpdatedAt    *string `json:"updated_at"`
}

type AppFile struct {
	ID          int64   `json:"id"`
	NodeID      int64   `json:"node_id"`
	Url         string  `json:"url"`
	Name        string  `json:"name"`
	Md5Hash     *string `json:"md5_hash"`
	Etag        *string `json:"etag"`
	RedirectUrl *string `json:"redirect_url"`
	LastUpdated *string `json:"last_updated"`
	LocalPath   *string `json:"local_path"`
	ObjectID    *string `json:"object_id"`
	RevisionID  *string `json:"revision_id"`
}

type AppFileStudy struct {
	CourseID    int64   `json:"course_id"`
	FilePath    string  `json:"file_path"`
	Level       int64   `json:"level"`
	LastUpdated *string `json:"last_updated"`
}

type AppFileVersion struct {
	ID                int64   `json:"id"`
	CourseID          int64   `json:"course_id"`
	FilePath          string  `json:"file_path"`
	VersionWebdavPath *string `json:"version_webdav_path"`
	ChangeType        string  `json:"change_type"`
	Timestamp         *string `json:"timestamp"`
	DisplayName       *string `json:"display_name"`
	RedirectUrl       *string `json:"redirect_url"`
	DiffWebdavPath    *string `json:"diff_webdav_path"`
	RevisionID        *string `json:"revision_id"`
	DiffRevisionID    *string `json:"diff_revision_id"`
	PdfDifferenceID   *string `json:"pdf_difference_id"`
}

type AppGlobalAnnouncement struct {
	ID             int64   `json:"id"`
	FeedKey        string  `json:"feed_key"`
	AnnouncementID string  `json:"announcement_id"`
	Title          string  `json:"title"`
	Link           string  `json:"link"`
	Description    *string `json:"description"`
	PubDate        *string `json:"pub_date"`
	FetchedAt      *string `json:"fetched_at"`
}

type AppNativeSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AppNode struct {
	ID        int64  `json:"id"`
	CourseID  int64  `json:"course_id"`
	ParentID  *int64 `json:"parent_id"`
	Name      string `json:"name"`
	Url       string `json:"url"`
	LocalPath string `json:"local_path"`
}

type AppNotificationLimit struct {
	TargetHash string             `json:"target_hash"`
	NextAt     pgtype.Timestamptz `json:"next_at"`
}

type AppNotificationMessage struct {
	ID          string             `json:"id"`
	EventKey    string             `json:"event_key"`
	Position    int32              `json:"position"`
	TargetHash  string             `json:"target_hash"`
	Content     string             `json:"content"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	Error       *string            `json:"error"`
}

type AppObject struct {
	ID        string             `json:"id"`
	Bucket    string             `json:"bucket"`
	Key       string             `json:"key"`
	VersionID string             `json:"version_id"`
	Sha256    string             `json:"sha256"`
	Bytes     int64              `json:"bytes"`
	MediaType string             `json:"media_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AppPdfDifference struct {
	ID          string             `json:"id"`
	CourseID    int64              `json:"course_id"`
	OldObjectID string             `json:"old_object_id"`
	NewObjectID string             `json:"new_object_id"`
	ToolVersion string             `json:"tool_version"`
	Status      string             `json:"status"`
	ObjectID    *string            `json:"object_id"`
	Error       *string            `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppPracticeAttempt struct {
	ID                    int64   `json:"id"`
	CourseID              int64   `json:"course_id"`
	UnitKey               string  `json:"unit_key"`
	QuestionID            string  `json:"question_id"`
	QuestionKey           string  `json:"question_key"`
	SetHash               string  `json:"set_hash"`
	BlueprintRevisionHash string  `json:"blueprint_revision_hash"`
	Outcome               string  `json:"outcome"`
	GradingMode           string  `json:"grading_mode"`
	Confidence            *int64  `json:"confidence"`
	Seconds               *int64  `json:"seconds"`
	Answer                *string `json:"answer"`
	Note                  *string `json:"note"`
	IdempotencyKey        *string `json:"idempotency_key"`
	StudyEventID          *int64  `json:"study_event_id"`
	AttemptedAt           *string `json:"attempted_at"`
}

type AppPreference struct {
	ID                         int64   `json:"id"`
	CheckIntervalMinutes       *int64  `json:"check_interval_minutes"`
	MaxConcurrentDownloads     *int64  `json:"max_concurrent_downloads"`
	RequestTimeoutSeconds      *int64  `json:"request_timeout_seconds"`
	RetryAttempts              *int64  `json:"retry_attempts"`
	NotificationEnabled        *int64  `json:"notification_enabled"`
	NotificationOnError        *int64  `json:"notification_on_error"`
	DownloadBasePath           string  `json:"download_base_path"`
	GlobalFeedDeptEnabled      *int64  `json:"global_feed_dept_enabled"`
	GlobalFeedUndergradEnabled *int64  `json:"global_feed_undergrad_enabled"`
	GlobalFeedRectorEnabled    *int64  `json:"global_feed_rector_enabled"`
	SemesterStart              *string `json:"semester_start"`
	SemesterEnd                *string `json:"semester_end"`
}

type AppSchemaVersion struct {
	ID        int64   `json:"id"`
	Version   int64   `json:"version"`
	UpdatedAt *string `json:"updated_at"`
}

type AppSnapshotFile struct {
	Path         string             `json:"path"`
	Sha256       string             `json:"sha256"`
	Bytes        int64              `json:"bytes"`
	Generation   string             `json:"generation"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

type AppStudyAnnotation struct {
	ID             int64   `json:"id"`
	CourseID       int64   `json:"course_id"`
	DocumentID     string  `json:"document_id"`
	SourceHash     string  `json:"source_hash"`
	PageNumber     int64   `json:"page_number"`
	Kind           string  `json:"kind"`
	Origin         string  `json:"origin"`
	Status         string  `json:"status"`
	Color          string  `json:"color"`
	Quote          string  `json:"quote"`
	Prefix         string  `json:"prefix"`
	Suffix         string  `json:"suffix"`
	CharStart      *int64  `json:"char_start"`
	CharEnd        *int64  `json:"char_end"`
	RectsJson      string  `json:"rects_json"`
	ChunkID        *string `json:"chunk_id"`
	Body           *string `json:"body"`
	TagsJson       string  `json:"tags_json"`
	ActionID       string  `json:"action_id"`
	UnitKey        string  `json:"unit_key"`
	PlanRevision   string  `json:"plan_revision"`
	SessionID      *int64  `json:"session_id"`
	IdempotencyKey *string `json:"idempotency_key"`
	CreatedAt      *string `json:"created_at"`
	UpdatedAt      *string `json:"updated_at"`
}

type AppStudyPlanItem struct {
	ID            int64   `json:"id"`
	CourseID      int64   `json:"course_id"`
	ScheduledDate string  `json:"scheduled_date"`
	Kind          string  `json:"kind"`
	Completed     int64   `json:"completed"`
	CreatedAt     *string `json:"created_at"`
}

type AppStudyPlannerSetting struct {
	ID                int64  `json:"id"`
	DailyBlocks       int64  `json:"daily_blocks"`
	BlockMinutes      int64  `json:"block_minutes"`
	WeeklyMinutesJson string `json:"weekly_minutes_json"`
	BlackoutDatesJson string `json:"blackout_dates_json"`
	MaxCoursesPerDay  int64  `json:"max_courses_per_day"`
}

type AppStudyReadingBeat struct {
	SessionID   int64   `json:"session_id"`
	Sequence    int64   `json:"sequence"`
	RecordedAt  *string `json:"recorded_at"`
	RequestHash *string `json:"request_hash"`
}

type AppStudyReadingSpan struct {
	ID             int64   `json:"id"`
	SessionID      int64   `json:"session_id"`
	CourseID       int64   `json:"course_id"`
	DocumentID     string  `json:"document_id"`
	SourceHash     string  `json:"source_hash"`
	PageNumber     int64   `json:"page_number"`
	ActionID       string  `json:"action_id"`
	UnitKey        string  `json:"unit_key"`
	PlanRevision   string  `json:"plan_revision"`
	ActiveSeconds  int64   `json:"active_seconds"`
	VisibleSeconds int64   `json:"visible_seconds"`
	StartedAt      *string `json:"started_at"`
	EndedAt        *string `json:"ended_at"`
}

type AppStudyReviewOverride struct {
	CourseID      int64  `json:"course_id"`
	ReviewOffset  int64  `json:"review_offset"`
	ScheduledDate string `json:"scheduled_date"`
}

type AppStudySession struct {
	ID        int64   `json:"id"`
	CourseID  int64   `json:"course_id"`
	Timestamp *string `json:"timestamp"`
	Note      *string `json:"note"`
}

type AppStudyUnitEvent struct {
	ID             int64    `json:"id"`
	CourseID       int64    `json:"course_id"`
	PlanRevision   string   `json:"plan_revision"`
	ActionID       string   `json:"action_id"`
	UnitKey        string   `json:"unit_key"`
	EventType      string   `json:"event_type"`
	IdempotencyKey *string  `json:"idempotency_key"`
	Confidence     *int64   `json:"confidence"`
	ActualMinutes  *int64   `json:"actual_minutes"`
	Score          *float64 `json:"score"`
	Note           *string  `json:"note"`
	CreatedAt      *string  `json:"created_at"`
}

type AppStudyWorkspaceSession struct {
	ID               int64   `json:"id"`
	CourseID         int64   `json:"course_id"`
	ActionID         string  `json:"action_id"`
	UnitKey          string  `json:"unit_key"`
	PlanRevision     string  `json:"plan_revision"`
	ClientSessionKey string  `json:"client_session_key"`
	PlannedMinutes   *int64  `json:"planned_minutes"`
	ActiveSeconds    int64   `json:"active_seconds"`
	VisibleSeconds   int64   `json:"visible_seconds"`
	Outcome          *string `json:"outcome"`
	Note             *string `json:"note"`
	StartedAt        *string `json:"started_at"`
	LastSeenAt       *string `json:"last_seen_at"`
	EndedAt          *string `json:"ended_at"`
	Confidence       *int64  `json:"confidence"`
	StudyEventID     *int64  `json:"study_event_id"`
}

type AppSyncStatus struct {
	Job         string  `json:"job"`
	LastRunAt   *string `json:"last_run_at"`
	LastResult  *string `json:"last_result"`
	LastError   *string `json:"last_error"`
	LastMessage *string `json:"last_message"`
}

type AppWebdavConfig struct {
	ID           int64  `json:"id"`
	Hostname     string `json:"hostname"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	DisableCheck *int64 `json:"disable_check"`
	Timeout      *int64 `json:"timeout"`
}

type AppWebhookConfig struct {
	ID         int64  `json:"id"`
	WebhookUrl string `json:"webhook_url"`
}

type KnowledgeArchiveMember struct {
	ChildDocumentID         string  `json:"child_document_id"`
	ParentDocumentID        string  `json:"parent_document_id"`
	MemberPath              string  `json:"member_path"`
	NormalizedMemberPath    string  `json:"normalized_member_path"`
	MemberChainJson         string  `json:"member_chain_json"`
	Depth                   int64   `json:"depth"`
	ArchiveFormat           string  `json:"archive_format"`
	ParentSourceHash        string  `json:"parent_source_hash"`
	ParentSourceFingerprint string  `json:"parent_source_fingerprint"`
	MemberHash              string  `json:"member_hash"`
	Crc32                   int64   `json:"crc32"`
	CompressedSize          int64   `json:"compressed_size"`
	ExpandedSize            int64   `json:"expanded_size"`
	MemberKind              string  `json:"member_kind"`
	MimeType                *string `json:"mime_type"`
}

type KnowledgeChunk struct {
	ID             string  `json:"id"`
	DocumentID     string  `json:"document_id"`
	Ordinal        int64   `json:"ordinal"`
	LocatorType    string  `json:"locator_type"`
	LocatorStart   *string `json:"locator_start"`
	LocatorEnd     *string `json:"locator_end"`
	Heading        *string `json:"heading"`
	Text           string  `json:"text"`
	NormalizedText string  `json:"normalized_text"`
	ContentHash    string  `json:"content_hash"`
	MetadataJson   string  `json:"metadata_json"`
}

type KnowledgeChunkEmbedding struct {
	ChunkID    string `json:"chunk_id"`
	Model      string `json:"model"`
	Vector     []byte `json:"vector"`
	Dimensions int64  `json:"dimensions"`
}

type KnowledgeChunksFt struct {
	ChunkID        string      `json:"chunk_id"`
	Text           *string     `json:"text"`
	NormalizedText *string     `json:"normalized_text"`
	Heading        *string     `json:"heading"`
	DisplayName    *string     `json:"display_name"`
	SourcePath     *string     `json:"source_path"`
	CourseName     *string     `json:"course_name"`
	SearchVector   interface{} `json:"search_vector"`
}

type KnowledgeCourseBlueprint struct {
	ID                   int64   `json:"id"`
	CourseID             int64   `json:"course_id"`
	Revision             int64   `json:"revision"`
	RevisionHash         string  `json:"revision_hash"`
	EvidenceHash         string  `json:"evidence_hash"`
	EvidencePacketJson   string  `json:"evidence_packet_json"`
	AnalysisVersion      string  `json:"analysis_version"`
	Status               string  `json:"status"`
	RequestedModel       string  `json:"requested_model"`
	Model                string  `json:"model"`
	PayloadJson          *string `json:"payload_json"`
	Priority             int64   `json:"priority"`
	Attempts             int64   `json:"attempts"`
	AvailableAt          string  `json:"available_at"`
	ClaimedAt            *string `json:"claimed_at"`
	CreatedAt            string  `json:"created_at"`
	GeneratedAt          *string `json:"generated_at"`
	FinishedAt           *string `json:"finished_at"`
	Error                *string `json:"error"`
	SupersededByRevision *int64  `json:"superseded_by_revision"`
}

type KnowledgeDocument struct {
	ID                  string  `json:"id"`
	CourseID            int64   `json:"course_id"`
	CourseName          string  `json:"course_name"`
	CourseShortName     *string `json:"course_short_name"`
	SourcePath          string  `json:"source_path"`
	SourceOrigin        string  `json:"source_origin"`
	NormalizedPath      string  `json:"normalized_path"`
	SourceUrl           *string `json:"source_url"`
	DisplayName         string  `json:"display_name"`
	SourceHash          string  `json:"source_hash"`
	SourceFingerprint   string  `json:"source_fingerprint"`
	SourceEtag          *string `json:"source_etag"`
	ContentHashVerified int64   `json:"content_hash_verified"`
	MimeType            *string `json:"mime_type"`
	ResponseMimeType    *string `json:"response_mime_type"`
	DocumentKind        string  `json:"document_kind"`
	AcademicYear        *string `json:"academic_year"`
	SourceModifiedAt    *string `json:"source_modified_at"`
	IsCurrent           int64   `json:"is_current"`
	Status              string  `json:"status"`
	PageCount           *int64  `json:"page_count"`
	SourceSizeBytes     *int64  `json:"source_size_bytes"`
	CharacterCount      *int64  `json:"character_count"`
	WordCount           *int64  `json:"word_count"`
	ReadingMinutes      *int64  `json:"reading_minutes"`
	ComplexityScore     *int64  `json:"complexity_score"`
	ComplexityLabel     *string `json:"complexity_label"`
	LanguageHint        *string `json:"language_hint"`
	ExtractorName       *string `json:"extractor_name"`
	ExtractorVersion    *string `json:"extractor_version"`
	IndexedAt           *string `json:"indexed_at"`
	Error               *string `json:"error"`
	DiagnosticReason    *string `json:"diagnostic_reason"`
	WarningsJson        string  `json:"warnings_json"`
}

type KnowledgeDocumentEnrichment struct {
	DocumentID      string  `json:"document_id"`
	SourceHash      string  `json:"source_hash"`
	ContextHash     string  `json:"context_hash"`
	AnalysisVersion string  `json:"analysis_version"`
	Status          string  `json:"status"`
	Model           string  `json:"model"`
	PayloadJson     *string `json:"payload_json"`
	Priority        int64   `json:"priority"`
	Attempts        int64   `json:"attempts"`
	AvailableAt     string  `json:"available_at"`
	ClaimedAt       *string `json:"claimed_at"`
	GeneratedAt     *string `json:"generated_at"`
	Error           *string `json:"error"`
	RequestedModel  *string `json:"requested_model"`
}

type KnowledgeIndexJob struct {
	ID             int64   `json:"id"`
	CourseID       int64   `json:"course_id"`
	SourcePath     string  `json:"source_path"`
	NormalizedPath string  `json:"normalized_path"`
	RequestedHash  string  `json:"requested_hash"`
	Action         string  `json:"action"`
	Status         string  `json:"status"`
	Attempts       int64   `json:"attempts"`
	AvailableAt    string  `json:"available_at"`
	ClaimedAt      *string `json:"claimed_at"`
	CompletedAt    *string `json:"completed_at"`
	Error          *string `json:"error"`
	ErrorCategory  *string `json:"error_category"`
	LastError      *string `json:"last_error"`
}

type KnowledgeKnowledgeSchemaVersion struct {
	ID        int64  `json:"id"`
	Version   int64  `json:"version"`
	UpdatedAt string `json:"updated_at"`
}

type KnowledgeKnowledgeState struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type KnowledgePageEnrichment struct {
	DocumentID      string  `json:"document_id"`
	PageNumber      int64   `json:"page_number"`
	SourceHash      string  `json:"source_hash"`
	AnalysisVersion string  `json:"analysis_version"`
	Status          string  `json:"status"`
	Model           string  `json:"model"`
	RequestedModel  string  `json:"requested_model"`
	PayloadJson     *string `json:"payload_json"`
	Priority        int64   `json:"priority"`
	Attempts        int64   `json:"attempts"`
	AvailableAt     string  `json:"available_at"`
	ClaimedAt       *string `json:"claimed_at"`
	GeneratedAt     *string `json:"generated_at"`
	Error           *string `json:"error"`
}

type KnowledgePracticeQuestion struct {
	QuestionID       string `json:"question_id"`
	SetID            int64  `json:"set_id"`
	CourseID         int64  `json:"course_id"`
	UnitKey          string `json:"unit_key"`
	Ordinal          int64  `json:"ordinal"`
	QuestionKey      string `json:"question_key"`
	ResponseMode     string `json:"response_mode"`
	Difficulty       string `json:"difficulty"`
	EstimatedMinutes int64  `json:"estimated_minutes"`
	PayloadJson      string `json:"payload_json"`
}

type KnowledgePracticeQuestionSet struct {
	ID                    int64   `json:"id"`
	CourseID              int64   `json:"course_id"`
	UnitKey               string  `json:"unit_key"`
	SetHash               string  `json:"set_hash"`
	BlueprintRevisionHash string  `json:"blueprint_revision_hash"`
	EvidenceHash          string  `json:"evidence_hash"`
	EvidencePacketJson    string  `json:"evidence_packet_json"`
	AnalysisVersion       string  `json:"analysis_version"`
	Status                string  `json:"status"`
	RequestedModel        string  `json:"requested_model"`
	Model                 string  `json:"model"`
	PayloadJson           *string `json:"payload_json"`
	Priority              int64   `json:"priority"`
	Attempts              int64   `json:"attempts"`
	AvailableAt           string  `json:"available_at"`
	ClaimedAt             *string `json:"claimed_at"`
	CreatedAt             string  `json:"created_at"`
	GeneratedAt           *string `json:"generated_at"`
	FinishedAt            *string `json:"finished_at"`
	Error                 *string `json:"error"`
}

type MessagesArchiveMedium struct {
	SourcePath   string `json:"source_path"`
	RelativePath string `json:"relative_path"`
	ObjectID     string `json:"object_id"`
}

type MessagesArchiveSource struct {
	Path        string  `json:"path"`
	RootID      string  `json:"root_id"`
	CourseID    int64   `json:"course_id"`
	Fingerprint string  `json:"fingerprint"`
	Sha256      *string `json:"sha256"`
	ChannelID   int64   `json:"channel_id"`
	ExportedAt  *string `json:"exported_at"`
	Status      string  `json:"status"`
	IndexedAt   string  `json:"indexed_at"`
	Error       *string `json:"error"`
	ObjectID    *string `json:"object_id"`
}

type MessagesChannel struct {
	ChannelID       int64   `json:"channel_id"`
	RootID          int64   `json:"root_id"`
	CourseID        int64   `json:"course_id"`
	GuildID         *int64  `json:"guild_id"`
	ChannelName     string  `json:"channel_name"`
	ChannelType     string  `json:"channel_type"`
	ParentChannelID *int64  `json:"parent_channel_id"`
	Topic           *string `json:"topic"`
	SourcePath      string  `json:"source_path"`
	ExportedAt      *string `json:"exported_at"`
}

type MessagesConversation struct {
	ConversationID   string  `json:"conversation_id"`
	CourseID         int64   `json:"course_id"`
	RootID           int64   `json:"root_id"`
	ChannelID        int64   `json:"channel_id"`
	ChannelName      string  `json:"channel_name"`
	ChannelType      string  `json:"channel_type"`
	FirstMessageID   int64   `json:"first_message_id"`
	LastMessageID    int64   `json:"last_message_id"`
	StartedAt        string  `json:"started_at"`
	EndedAt          string  `json:"ended_at"`
	EndedAtEpoch     float64 `json:"ended_at_epoch"`
	Text             string  `json:"text"`
	NormalizedText   string  `json:"normalized_text"`
	ParticipantCount int64   `json:"participant_count"`
	ReactionCount    int64   `json:"reaction_count"`
	IsPinned         int64   `json:"is_pinned"`
	MetadataJson     string  `json:"metadata_json"`
	SourcePath       string  `json:"source_path"`
}

type MessagesConversationEmbedding struct {
	ConversationID string `json:"conversation_id"`
	Model          string `json:"model"`
	Vector         []byte `json:"vector"`
	Dimensions     int64  `json:"dimensions"`
}

type MessagesConversationMessage struct {
	ConversationID string `json:"conversation_id"`
	MessageID      int64  `json:"message_id"`
	SourcePath     string `json:"source_path"`
	Position       int64  `json:"position"`
}

type MessagesConversationsFt struct {
	ConversationID string      `json:"conversation_id"`
	Text           *string     `json:"text"`
	NormalizedText *string     `json:"normalized_text"`
	ChannelName    *string     `json:"channel_name"`
	SearchVector   interface{} `json:"search_vector"`
}

type MessagesExportCursor struct {
	RootID    int64              `json:"root_id"`
	ChannelID int64              `json:"channel_id"`
	AfterID   int64              `json:"after_id"`
	NextAt    pgtype.Timestamptz `json:"next_at"`
	Error     *string            `json:"error"`
}

type MessagesMessage struct {
	MessageID              int64   `json:"message_id"`
	ChannelID              int64   `json:"channel_id"`
	CourseID               int64   `json:"course_id"`
	Timestamp              string  `json:"timestamp"`
	TimestampEpoch         float64 `json:"timestamp_epoch"`
	AuthorKey              *string `json:"author_key"`
	AuthorName             string  `json:"author_name"`
	Content                string  `json:"content"`
	SearchableText         string  `json:"searchable_text"`
	ReplyToMessageID       *int64  `json:"reply_to_message_id"`
	MessageType            string  `json:"message_type"`
	IsPinned               int64   `json:"is_pinned"`
	ReactionCount          int64   `json:"reaction_count"`
	AttachmentMetadataJson string  `json:"attachment_metadata_json"`
	SourcePath             string  `json:"source_path"`
}

type MessagesMessageSchemaVersion struct {
	ID        int64  `json:"id"`
	Version   int64  `json:"version"`
	UpdatedAt string `json:"updated_at"`
}

type MessagesMessageState struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type ReadModelActionProgress struct {
	CourseID        int64  `json:"course_id"`
	ActionID        string `json:"action_id"`
	LatestEvent     string `json:"latest_event"`
	ProgressMinutes int64  `json:"progress_minutes"`
}

type ReadModelCourseCoverage struct {
	CourseID          int64  `json:"course_id"`
	PayloadJson       string `json:"payload_json"`
	GeneratedAt       string `json:"generated_at"`
	Generation        int64  `json:"generation"`
	LearnerGeneration int64  `json:"learner_generation"`
	RecentJson        []byte `json:"recent_json"`
}

type ReadModelCourseGeneration struct {
	CourseID   int64 `json:"course_id"`
	Generation int64 `json:"generation"`
}

type ReadModelLearnerGeneration struct {
	CourseID   int64 `json:"course_id"`
	Generation int64 `json:"generation"`
}

type ReadModelNavigation struct {
	CourseID         int64              `json:"course_id"`
	SourceGeneration int64              `json:"source_generation"`
	ConfigGeneration string             `json:"config_generation"`
	RevisionID       *string            `json:"revision_id"`
	Overview         []byte             `json:"overview"`
	ContentID        string             `json:"content_id"`
	GeneratedAt      pgtype.Timestamptz `json:"generated_at"`
}

type ReadModelReadModelMetadatum struct {
	ID          int64   `json:"id"`
	Generation  int64   `json:"generation"`
	GeneratedAt string  `json:"generated_at"`
	Status      string  `json:"status"`
	LastError   *string `json:"last_error"`
}

type ReadModelRecentMaterial struct {
	Ordinal     int64  `json:"ordinal"`
	CourseID    int64  `json:"course_id"`
	PayloadJson string `json:"payload_json"`
	GeneratedAt string `json:"generated_at"`
	Generation  int64  `json:"generation"`
}

type ReadModelRoadmapAction struct {
	CourseID int64  `json:"course_id"`
	ActionID string `json:"action_id"`
	Ordinal  int64  `json:"ordinal"`
	UnitKey  string `json:"unit_key"`
	Payload  []byte `json:"payload"`
}

type ReadModelRoadmapContent struct {
	ContentID string `json:"content_id"`
	Payload   []byte `json:"payload"`
}

type ReadModelStudyMetric struct {
	Scope             string             `json:"scope"`
	PayloadJson       string             `json:"payload_json"`
	GeneratedAt       string             `json:"generated_at"`
	Generation        int64              `json:"generation"`
	SourceFingerprint string             `json:"source_fingerprint"`
	Status            string             `json:"status"`
	RetryAfter        pgtype.Timestamptz `json:"retry_after"`
}

type ReadModelSynthesisScan struct {
	CourseID         int64              `json:"course_id"`
	Lane             string             `json:"lane"`
	SourceGeneration int64              `json:"source_generation"`
	ConfigGeneration string             `json:"config_generation"`
	NextAt           pgtype.Timestamptz `json:"next_at"`
}
